#!/usr/bin/env bash
# shellcheck source-path=SCRIPTDIR
# lib/setup/migrate.sh: kit/setup.sh migrate. Moves a workspace from the 2.x layout (the kit checked
# out at another path, its plugins vendored into .claude/plugins, generated skills in skills/, copies
# of kit files beside the team's own) to the 3.0 layout, where the kit is a submodule at kit/ and is
# read in place.
#
#   migrate.sh --target WS [--dry-run] [--map FILE] [--kit-from URL] [--kit-ref REF]
#              [--allow-staged] [--developer] [--confirm-private-origin]
#
# It knows only the kit's own moves. A workspace's own moves (folders renamed, content untracked,
# references rewritten) come from a map file, whose format is in kit/docs/migration.md.
#
# How it behaves:
#   - Every action prints one line, naming what it does, before it does it. The verbs are move,
#     retire, edit, config, run, note and skip. A dry run prints the same lines with "would " in front
#     and changes nothing in the workspace.
#   - Nothing is deleted. "retire" takes a path out of the index (when it is tracked) and moves it
#     under _delete/, which is gitignored; a person deletes it.
#   - Each step checks whether it is already done, so a second run prints only skip lines, and a run
#     stopped partway resumes.
#   - Nothing is committed. The run ends with the commit to make, by path.
#   - Opaque files (AW_OPAQUE_PATHS, by default AGENTS.md and copilot-instructions.md) are never read,
#     written, moved or renamed.
#
# The dry run and the real run print the same lines. To make that true without touching the
# workspace, a dry run keeps a small overlay in a temporary folder: the files it would have edited
# (the "shadow"), and a list of the moves and removals it would have made (the "ops"). Every later
# step reads the workspace through that overlay, so it sees what the real run would see at that point.
#
# Exit codes: 0 complete (or a dry run); 1 a precondition; 2 usage or a malformed map; 3 stopped at a
# failing step, which it names. The script runs under bash 3.2 and needs git and jq.
set -uo pipefail

MG_SELF_KIT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"
# shellcheck source=../common.sh
. "$MG_SELF_KIT/lib/common.sh"

MG_DEFAULT_URL="https://github.com/cyberscribe/agentic-workspace-kit.git"
MG_MARKER="Generated by install.sh from plugins/"
MG_IMPORT="@kit/CLAUDE.kit.md"
# The backticks in these strings are Markdown, written literally.
# shellcheck disable=SC2016
MG_FALLBACK='Kit working standards: `kit/CLAUDE.kit.md` (read it at session start if the line above was not expanded).'
MG_KIT_HEADER="# Added by the agentic workspace kit (kit/templates/workspace.gitignore)"

mg_usage() {
    cat <<'EOF'
Usage: kit/setup.sh migrate [--target DIR] [--dry-run] [--map FILE] [--kit-from URL] [--kit-ref REF]
                            [--allow-staged] [--developer] [--confirm-private-origin]

Moves a 2.x workspace to the 3.0 layout: the kit becomes the submodule at kit/, the vendored plugins,
generated skills and unchanged copies of kit files move to _delete/, references to the old kit path
are rewritten, the hooks and submodule settings are set, and the files the kit now leaves to you are
created. Every action is printed before it is made; nothing is deleted and nothing is committed.

  --dry-run                  print what would happen, and change nothing
  --map FILE                 the workspace's own moves (format: kit/docs/migration.md); keep it
                             outside kit/
  --kit-from URL             bring the kit checkout to REF from URL first (also AW_KIT_URL)
  --kit-ref REF              the kit commit, branch or tag to migrate to (default main)
  --allow-staged             run although the index has staged changes
  --developer                also put kit/ on main for kit development (kit/setup.sh --developer)
  --confirm-private-origin   record origin as a private remote you have confirmed yourself, in
                             .claude/workspace.md under Private remotes

Run it with --dry-run first, then without.
EOF
}

# ---- Arguments -----------------------------------------------------------------------------------
WS="" DRY=0 MAP="" KIT_FROM="${AW_KIT_URL:-}" KIT_REF="main" ALLOW_STAGED=0 DEVELOPER=0 CONFIRM_ORIGIN=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        --target) [[ $# -ge 2 ]] || { mg_usage >&2; exit 2; }; WS="$2"; shift 2 ;;
        --target=*) WS="${1#--target=}"; shift ;;
        --dry-run) DRY=1; shift ;;
        --map) [[ $# -ge 2 ]] || { mg_usage >&2; exit 2; }; MAP="$2"; shift 2 ;;
        --map=*) MAP="${1#--map=}"; shift ;;
        --kit-from) [[ $# -ge 2 ]] || { mg_usage >&2; exit 2; }; KIT_FROM="$2"; shift 2 ;;
        --kit-from=*) KIT_FROM="${1#--kit-from=}"; shift ;;
        --kit-ref) [[ $# -ge 2 ]] || { mg_usage >&2; exit 2; }; KIT_REF="$2"; shift 2 ;;
        --kit-ref=*) KIT_REF="${1#--kit-ref=}"; shift ;;
        --allow-staged) ALLOW_STAGED=1; shift ;;
        --developer) DEVELOPER=1; shift ;;
        --confirm-private-origin) CONFIRM_ORIGIN=1; shift ;;
        -h|--help) mg_usage; exit 0 ;;
        *) printf 'migrate: unknown option %s\n\n' "$1" >&2; mg_usage >&2; exit 2 ;;
    esac
done
[[ -n "$WS" ]] || { printf 'migrate: --target is required\n\n' >&2; mg_usage >&2; exit 2; }
[[ -d "$WS" ]] || { printf 'migrate: %s is not a folder\n' "$WS" >&2; exit 1; }
WS="$(cd "$WS" && pwd -P)"

for mg_tool in git jq; do
    command -v "$mg_tool" >/dev/null 2>&1 || { printf 'migrate: needs %s on PATH\n' "$mg_tool" >&2; exit 1; }
done

# A temporary folder for the dry run's overlay and for scratch files. AW_KEEP=1 leaves it in place.
MG_TMP="$(mktemp -d "${TMPDIR:-/tmp}/aw-migrate.XXXXXX")" || { echo "migrate: cannot create a temporary folder" >&2; exit 1; }
if [[ "${AW_KEEP:-}" != "1" ]]; then trap 'rm -rf "$MG_TMP"' EXIT; fi
SHADOW="$MG_TMP/shadow" OPS="$MG_TMP/ops"
mkdir -p "$SHADOW" && : > "$OPS"

# ---- Git helpers ---------------------------------------------------------------------------------
# Reads in the workspace never take optional locks; writes go through mg_gw.
mg_g()  { git --no-optional-locks -C "$WS" "$@"; }
mg_gw() { git -C "$WS" "$@"; }

# A URL with no scheme and no scp form is a local path; git clones and fetches of one need the file
# protocol allowed explicitly. mg_proto URL sets MG_PC to that setting, or to nothing.
MG_PC=""
mg_proto() { MG_PC=""; case "$(aw_norm_url "$1")" in local:*) MG_PC="protocol.file.allow=always" ;; esac; }

# ---- Output --------------------------------------------------------------------------------------
# mg_act VERB TEXT: one action line; in a dry run, "would " comes first.
MG_ACTED=0
mg_act() {
    case "$1" in skip|note) ;; *) MG_ACTED=$((MG_ACTED + 1)) ;; esac
    if [[ $DRY -eq 1 ]]; then printf 'would %s %s\n' "$1" "$2"; else printf '%s %s\n' "$1" "$2"; fi
}
# mg_do VERB TEXT: an action line that does not count as a change to the workspace (bringing the kit
# checkout to the version to migrate to).
mg_do() { printf '%s %s\n' "$1" "$2"; }
# mg_would VERB TEXT: the dry run's line for an mg_do action, which it does not make.
mg_would() { printf 'would %s %s\n' "$1" "$2"; }
# mg_preview CMD...: in a dry run, what a step handed to another script would change, indented under
# its would-run line: the child's own check output, with "would " before each "set" line.
mg_preview() { "$@" 2>/dev/null | sed -e 's/^set /would set /' -e 's/^/    /'; return 0; }
# mg_child CMD...: a child's output, indented under the run line that names it.
mg_child() { "$@" 2>&1 | sed 's/^/    /'; return "${PIPESTATUS[0]}"; }

MG_STAGED_MARK=""
mg_mark_staged() {
    [[ $DRY -eq 1 || -z "$MG_STAGED_MARK" ]] && return 0
    mg_g ls-files -s 2>/dev/null | git hash-object --stdin > "$MG_STAGED_MARK" 2>/dev/null
    return 0
}
mg_stop() {
    printf 'migrate: stopped at %s: %s\n' "$1" "$2" >&2
    printf 'Nothing after this step was done. Fix the cause and run the migration again; it resumes.\n' >&2
    mg_mark_staged
    mg_save_state "$1"
    exit 3
}

# A run that stops leaves what the commit plan and the leftover-reference check (M18) need in
# aw-migrate-state, beside aw-migrate-index: the paths to add, the staged moves and removals, the
# moves. The run that resumes reads it back while HEAD has not moved, so its plan and its M18 cover the
# whole migration and not only its own part. A run that finishes removes the file.
MG_STATE_FILE="" MG_PRIOR_ACTED=0 MG_PRIOR_STOP=""
mg_save_state() {
    local p i
    [[ $DRY -eq 1 || -z "$MG_STATE_FILE" ]] && return 0
    {
        printf 'head\t%s\n' "$(mg_g rev-parse -q --verify HEAD 2>/dev/null)"
        printf 'stopped\t%s\n' "$1"
        printf 'acted\t%s\n' "$((MG_ACTED + MG_PRIOR_ACTED))"
        [[ $MG_EDITED_GITIGNORE -eq 1 ]] && printf 'gitignore\t1\n'
        for p in ${MG_PLAN[@]+"${MG_PLAN[@]}"}; do printf 'P\t%s\n' "$p"; done
        for p in ${MG_STAGED[@]+"${MG_STAGED[@]}"}; do printf 'S\t%s\n' "$p"; done
        i=0
        while [[ $i -lt ${#MG_MOVED_FROM[@]} ]]; do
            printf 'M\t%s\t%s\n' "${MG_MOVED_FROM[$i]}" "${MG_MOVED_TO[$i]}"
            i=$((i + 1))
        done
    } > "$MG_STATE_FILE" 2>/dev/null
    return 0
}

# Quoting for a path in a command printed for a person: single quotes when it needs any.
mg_q() { case "$1" in *[!A-Za-z0-9._/@:+=,-]*) printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")" ;; *) printf '%s' "$1" ;; esac; }

# ---- The workspace as the run sees it ------------------------------------------------------------
# In a real run these read the workspace directly. In a dry run they read it through the overlay:
# the ops file records "M<TAB>from<TAB>to" (a move), "G<TAB>path" (retired) and "U<TAB>path"
# (untracked); the shadow folder holds edited copies at their workspace-relative paths.

# mg_vorig PATH: sets MG_ORIG to the path in the real tree that PATH stands for, and MG_UNTR to 1 when
# an untrack covers it. Returns 1 when PATH has been moved away or retired.
MG_ORIG="" MG_UNTR=0
mg_vorig() {
    local p="$1" t a b
    MG_UNTR=0
    if [[ $DRY -eq 1 && -s "$OPS" ]]; then
        while IFS=$'\t' read -r t a b; do
            case "$t" in
                M) if [[ "$p" == "$b" || "$p" == "$b/"* ]]; then p="$a${p#"$b"}"; continue; fi
                   if [[ "$p" == "$a" || "$p" == "$a/"* ]]; then return 1; fi ;;
                G) if [[ "$p" == "$a" || "$p" == "$a/"* ]]; then return 1; fi ;;
                U) if [[ "$p" == "$a" || "$p" == "$a/"* ]]; then MG_UNTR=1; fi ;;
            esac
        done < <(awk '{ l[NR] = $0 } END { for (i = NR; i >= 1; i--) print l[i] }' "$OPS")
    fi
    MG_ORIG="$p"
    return 0
}
mg_vexists() {
    [[ $DRY -eq 1 && -e "$SHADOW/$1" ]] && return 0
    mg_vorig "$1" || return 1
    [[ -e "$WS/$MG_ORIG" || -L "$WS/$MG_ORIG" ]]
}
# mg_vphys PATH: the file to read for PATH (the shadow copy when there is one).
mg_vphys() {
    if [[ $DRY -eq 1 && -e "$SHADOW/$1" ]]; then printf '%s\n' "$SHADOW/$1"; return 0; fi
    mg_vorig "$1" || return 1
    printf '%s\n' "$WS/$MG_ORIG"
}
mg_vread() { local f; f="$(mg_vphys "$1")" || return 1; [[ -f "$f" ]] || return 1; cat "$f"; }
# mg_vwrite PATH: stdin becomes PATH (in the shadow, in a dry run). The file keeps its mode.
mg_vwrite() {
    local dest="$WS/$1"
    if [[ $DRY -eq 1 ]]; then
        dest="$SHADOW/$1"
        if [[ ! -e "$dest" ]]; then mkdir -p "$(dirname "$dest")"; fi
    else
        mkdir -p "$(dirname "$dest")"
    fi
    cat > "$dest"
}
# mg_vtracked PATH: 0 when anything at or under PATH is tracked (a gitlink included).
mg_vtracked() {
    mg_vorig "$1" || return 1
    [[ $MG_UNTR -eq 0 ]] || return 1
    [[ -n "$(mg_g ls-files -- "$MG_ORIG" 2>/dev/null | head -n 1)" ]]
}
mg_vgitlink() {
    mg_vorig "$1" || return 1
    [[ $MG_UNTR -eq 0 ]] || return 1
    mg_g ls-files -s -- "$MG_ORIG" 2>/dev/null | awk -v p="$MG_ORIG" '$1 == "160000" && substr($0, index($0, "\t") + 1) == p { f = 1 } END { exit !f }'
}
mg_op() { [[ $DRY -eq 1 ]] && printf '%s\n' "$*" >> "$OPS"; return 0; }
# A dry-run move carries the shadow copies with it.
mg_shadow_move() {
    [[ $DRY -eq 1 && -e "$SHADOW/$1" ]] || return 0
    mkdir -p "$(dirname "$SHADOW/$2")" && mv "$SHADOW/$1" "$SHADOW/$2"
}

# mg_vlist: "path<TAB>file" for every tracked file (gitlinks and symlinks left out) as the tree stands
# now in this run: the path in the workspace, and the file to read for it.
mg_vlist() {
    local shl="$MG_TMP/shadow-list"
    : > "$shl"
    if [[ $DRY -eq 1 ]]; then (cd "$SHADOW" && find . -type f | sed 's#^\./##') > "$shl"; fi
    mg_g ls-files -s -z 2>/dev/null | tr '\0' '\n' | awk -v dry="$DRY" -v ops="$OPS" -v sh="$SHADOW" -v ws="$WS" -v shl="$shl" '
        BEGIN {
            n = 0
            if (dry) {
                while ((getline l < ops) > 0) { n++; split(l, f, "\t"); T[n] = f[1]; A[n] = f[2]; B[n] = f[3] }
                while ((getline l < shl) > 0) S[l] = 1
            }
        }
        {
            # Gitlinks are other repositories; a tracked symlink may point into a cloud drive.
            split($0, m, " "); if (m[1] == "160000" || m[1] == "120000") next
            o = substr($0, index($0, "\t") + 1); if (seen[o]++) next
            p = o
            for (i = 1; i <= n; i++) {
                if (p == A[i] || index(p, A[i] "/") == 1) {
                    if (T[i] == "M") p = B[i] substr(p, length(A[i]) + 1)
                    else { p = ""; break }
                }
            }
            if (p == "") next
            print p "\t" ((p in S) ? sh "/" p : ws "/" o)
        }'
}

# The opaque files that exist here. They are never opened, so every scan leaves them out.
MG_OPAQUE=()
mg_opaque_init() {
    local list p
    if [[ -n "${AW_OPAQUE_PATHS+set}" ]]; then list="$AW_OPAQUE_PATHS"; else list="AGENTS.md copilot-instructions.md"; fi
    for p in $list; do aw_is_opaque "$WS" "$p" && MG_OPAQUE+=("$p"); done
    return 0
}
mg_is_opaque() { local o; for o in ${MG_OPAQUE[@]+"${MG_OPAQUE[@]}"}; do [[ "$1" == "$o" ]] && return 0; done; return 1; }
# A path that is, holds, or sits inside an opaque file.
mg_touches_opaque() {
    local o
    for o in ${MG_OPAQUE[@]+"${MG_OPAQUE[@]}"}; do
        [[ "$1" == "$o" || "$o" == "$1/"* || "$1" == "$o/"* ]] && return 0
    done
    return 1
}
# Dated records keep their wording: logs/, _delete/, projects/_done/, any file named for decisions, and
# what a map's historical lines name.
MG_HIST_GLOBS=()
mg_is_historical() {
    case "$1" in logs/*|_delete/*|projects/_done/*) return 0 ;; esac
    case "${1##*/}" in *decisions*) return 0 ;; esac
    mg_map_historical "$1"
}
# A path a map's historical line names: its glob matches the path, or a folder it matches holds it.
# Glob matching as git's default pathspec does it: * crosses folders.
mg_map_historical() {
    local g
    for g in ${MG_HIST_GLOBS[@]+"${MG_HIST_GLOBS[@]}"}; do
        # shellcheck disable=SC2053
        [[ "$1" == $g || "$1" == $g/* ]] && return 0
    done
    return 1
}

# mg_candidates FIXED [scope]: "path<TAB>file" for tracked text files that contain FIXED, outside the
# kit, opaque files and .gitmodules. Scope "all" keeps historical records in; "globs" takes the
# globs in MG_GLOBS instead of the default set; "ext" limits to the extensions the kit path rewrite
# reads.
MG_GLOBS=()
mg_candidates() {
    local fixed="$1" scope="${2:-all}" list="$MG_TMP/cand-list" pre="$MG_TMP/cand-pre" hits="$MG_TMP/cand-hits"
    local vp ph g keep
    : > "$list"
    # The fixed exclusions in one pass: the kit, .gitmodules, opaque files, and (for "ext") the file
    # types the kit path rewrite reads.
    mg_vlist | awk -F '\t' -v scope="$scope" -v opq="${MG_OPAQUE[*]+${MG_OPAQUE[*]}}" '
        BEGIN { n = split(opq, O, " ") }
        {
            vp = $1
            if (vp == "kit" || index(vp, "kit/") == 1 || vp == ".gitmodules") next
            for (i = 1; i <= n; i++) if (vp == O[i] || index(vp, O[i] "/") == 1) next
            if (scope == "ext" && vp !~ /\.(md|json|sh|py|txt|yml)$/) next
            print
        }' > "$pre"
    if [[ "$scope" == globs ]]; then
        while IFS=$'\t' read -r vp ph; do
            keep=0
            for g in ${MG_GLOBS[@]+"${MG_GLOBS[@]}"}; do
                # Glob matching as git's default pathspec does it: * crosses folders.
                # shellcheck disable=SC2053
                [[ "$vp" == $g ]] && { keep=1; break; }
            done
            [[ $keep -eq 1 ]] && printf '%s\t%s\n' "$vp" "$ph" >> "$list"
        done < "$pre"
    else
        cat "$pre" > "$list"
    fi
    [[ -s "$list" ]] || return 0
    cut -f 2 "$list" | tr '\n' '\0' | xargs -0 grep -l -I -F -e "$fixed" -- > "$hits" 2>/dev/null
    awk -F '\t' -v hits="$hits" 'BEGIN { while ((getline l < hits) > 0) H[l] = 1 } ($2 in H)' "$list"
}

# mg_replace FILE OUT FROM TO MODE [KEEPFILE]: writes FILE with FROM replaced by TO to OUT and prints
# the numbers of the lines it changed. MODE "any" replaces every occurrence; "path" only where FROM
# follows the start of a line, a space, a tab, ( [ ` ' " or /; "word" the same without /; "ref" as
# "path", and not followed by a letter, a digit, _ or - (a whole path, for the leftover check). An
# occurrence inside a literal listed in KEEPFILE, or inside an occurrence of TO (text already
# rewritten), is left alone. With OUT empty it only reports.
mg_replace() {
    awk -v from="$3" -v to="$4" -v mode="$5" -v keepf="${6:-}" -v out="$2" '
        BEGIN {
            nk = 0
            if (keepf != "") while ((getline l < keepf) > 0) if (l != "") K[++nk] = l
            if (to != "" && index(to, from)) K[++nk] = to
            bset = " \t([`\047\""; if (mode == "path" || mode == "ref") bset = bset "/"
            lf = length(from)
        }
        function protect(line, lit,    s, i, p, k) {
            s = 1
            while ((i = index(substr(line, s), lit)) > 0) {
                p = s + i - 1
                for (k = p; k < p + length(lit); k++) PR[k] = 1
                s = p + 1
            }
        }
        {
            line = $0; split("", PR)
            for (j = 1; j <= nk; j++) protect(line, K[j])
            res = ""; s = 1; changed = 0
            while ((i = index(substr(line, s), from)) > 0) {
                p = s + i - 1; ok = 1
                for (k = p; k < p + lf; k++) if (k in PR) { ok = 0; break }
                if (ok && mode != "any" && p > 1 && index(bset, substr(line, p - 1, 1)) == 0) ok = 0
                if (ok && mode == "ref" && substr(from, lf, 1) != "/" && substr(line, p + lf, 1) ~ /[A-Za-z0-9_-]/) ok = 0
                if (ok) { res = res substr(line, s, p - s) to; s = p + lf; changed = 1 }
                else { res = res substr(line, s, p - s + 1); s = p + 1 }
            }
            res = res substr(line, s)
            if (out != "") print res > out
            if (changed) print NR
        }' "$1"
}

# ---- .gitignore ----------------------------------------------------------------------------------
mg_ignore_has() { mg_vread .gitignore 2>/dev/null | awk -v l="$1" '{ sub(/[ \t]+$/, "") } $0 == l { f = 1 } END { exit !f }'; }
# mg_ignore_add LINE [kit]: appends LINE; with "kit", under the kit's header, written once.
mg_ignore_add() {
    local line="$1" kit="${2:-}" cur="$MG_TMP/gi"
    mg_vread .gitignore > "$cur" 2>/dev/null || : > "$cur"
    if [[ -s "$cur" && -n "$(tail -c 1 "$cur")" ]]; then printf '\n' >> "$cur"; fi
    if [[ "$kit" == kit ]] && ! grep -qxF "$MG_KIT_HEADER" "$cur"; then
        [[ -s "$cur" ]] && printf '\n' >> "$cur"
        printf '%s\n' "$MG_KIT_HEADER" >> "$cur"
    fi
    printf '%s\n' "$line" >> "$cur"
    mg_vwrite .gitignore < "$cur"
    MG_EDITED_GITIGNORE=1
}
MG_EDITED_GITIGNORE=0
# _delete/ is ignored before anything is moved into it, so a broad git add never sweeps it up.
mg_ensure_delete_ignored() {
    mg_ignore_has "_delete/" && return 0
    mg_ignore_has "/_delete/" && return 0
    mg_act edit ".gitignore: + _delete/ (what the migration retires waits there for a person to delete it)"
    mg_ignore_add "_delete/" kit
}
# mg_ignored_by PATH: the .gitignore line that ignores PATH, as source:line:pattern, or nothing.
mg_ignored_by() { mg_g check-ignore -v --no-index -- "$1" 2>/dev/null | awk -F '\t' '{ print $1; exit }'; }

# ---- Actions -------------------------------------------------------------------------------------
MG_PLAN=()        # paths to name in the git add line
MG_STAGED=()      # removals and moves the migration staged itself
MG_MOVED_FROM=()  # sources of moves, for the leftover-reference check (M18)
MG_MOVED_TO=()
MG_EDITED=()
mg_plan() { MG_PLAN+=("$1"); }

# mg_retire STEP PATH: out of the index when tracked, then moved under _delete/.
mg_retire() {
    local step="$1" p="$2" dest="_delete/$2"
    if mg_touches_opaque "$p"; then mg_act skip "$step $p (opaque here: left as it is)"; return 0; fi
    if ! mg_vexists "$p"; then mg_act skip "$step $p (not present here)"; return 0; fi
    if mg_vexists "$dest"; then mg_act skip "$step $p (destination exists: $dest)"; return 0; fi
    mg_ensure_delete_ignored
    mg_act retire "$p -> $dest"
    if [[ $DRY -eq 1 ]]; then
        mg_op "G	$p"
    else
        if mg_vtracked "$p"; then
            mg_gw rm -r --cached -q -- "$p" || mg_stop "$step" "git rm --cached $p failed"
        fi
        if ! { mkdir -p "$WS/$(dirname "$dest")" && mv "$WS/$p" "$WS/$dest"; }; then mg_stop "$step" "moving $p to $dest failed"; fi
    fi
    MG_STAGED+=("$p"); MG_MOVED_FROM+=("$p"); MG_MOVED_TO+=("kit/$p")
    return 0
}

# mg_move STEP FROM TO HOW: HOW is "git mv" or "mv". Parents of TO are created.
mg_move() {
    local step="$1" from="$2" to="$3" how="$4"
    mg_act move "$from -> $to ($how)"
    if [[ $DRY -eq 1 ]]; then
        mg_op "M	$from	$to"
        mg_shadow_move "$from" "$to"
    else
        mkdir -p "$WS/$(dirname "$to")" || mg_stop "$step" "cannot create the folder for $to"
        if [[ "$how" == "git mv" ]]; then
            mg_gw mv -- "$from" "$to" || mg_stop "$step" "git mv $from $to failed"
        else
            mv "$WS/$from" "$WS/$to" || mg_stop "$step" "mv $from $to failed"
        fi
    fi
    MG_MOVED_FROM+=("$from"); MG_MOVED_TO+=("$to")
    if [[ "$how" == "git mv" ]]; then MG_STAGED+=("$from"); fi
    mg_plan "$to"
}

# mg_rewrite_in PATH FROM TO MODE [KEEPFILE] [LABEL]: rewrites one file, one edit line per line
# changed.
mg_rewrite_in() {
    local vp="$1" from="$2" to="$3" mode="$4" keepf="${5:-}" ph out="$MG_TMP/rw-out" nums n
    ph="$(mg_vphys "$vp")" || return 0
    nums="$(mg_replace "$ph" "$out" "$from" "$to" "$mode" "$keepf")"
    [[ -n "$nums" ]] || return 0
    for n in $nums; do mg_act edit "$vp:$n $from -> $to"; done
    mg_vwrite "$vp" < "$out"
    MG_EDITED+=("$vp"); mg_plan "$vp"
}

# ---- Preconditions -------------------------------------------------------------------------------
mg_g rev-parse --git-dir >/dev/null 2>&1 || { printf 'migrate: %s is not a git repository\n' "$WS" >&2; exit 1; }
[[ "$(mg_g rev-parse --show-toplevel 2>/dev/null)" == "$WS" ]] || {
    printf 'migrate: %s is inside another repository; --target names the workspace root\n' "$WS" >&2; exit 1; }
case "$WS/" in "$MG_SELF_KIT"/*) printf 'migrate: the target is inside the kit checkout; --target names the workspace\n' >&2; exit 1 ;; esac
MG_STAGED_MARK="$(mg_g rev-parse --absolute-git-dir 2>/dev/null)/aw-migrate-index"
MG_STATE_FILE="${MG_STAGED_MARK%/*}/aw-migrate-state"
if [[ $DRY -eq 0 && -s "$MG_STATE_FILE" ]] \
    && [[ "$(awk -F '\t' '$1 == "head" { print $2; exit }' "$MG_STATE_FILE")" == "$(mg_g rev-parse -q --verify HEAD 2>/dev/null)" ]]; then
    while IFS=$'\t' read -r mg_t mg_a mg_b; do
        case "$mg_t" in
            stopped) MG_PRIOR_STOP="$mg_a" ;;
            acted) [[ "$mg_a" =~ ^[0-9]+$ ]] && MG_PRIOR_ACTED="$mg_a" ;;
            gitignore) MG_EDITED_GITIGNORE=1 ;;
            P) MG_PLAN+=("$mg_a") ;;
            S) MG_STAGED+=("$mg_a") ;;
            M) MG_MOVED_FROM+=("$mg_a"); MG_MOVED_TO+=("$mg_b") ;;
        esac
    done < "$MG_STATE_FILE"
fi
mg_opaque_init

# The staged changes a run leaves behind are recorded, so a rerun (to resume, or to check that
# nothing is left) is not refused for them.
if ! mg_g diff --cached --quiet 2>/dev/null; then
    mg_now="$(mg_g ls-files -s 2>/dev/null | git hash-object --stdin 2>/dev/null)"
    if [[ -f "$MG_STAGED_MARK" && "$(cat "$MG_STAGED_MARK")" == "$mg_now" ]]; then
        echo "The staged changes are an earlier run of this migration's own; they stay staged."
    elif [[ $ALLOW_STAGED -eq 0 ]]; then
        printf 'migrate: the index has staged changes. Commit or unstage them first, or pass --allow-staged.\n' >&2
        exit 1
    fi
fi

# The kit checkout: the submodule at kit/, else the one the settings name as the plugin marketplace,
# else one whose checkout is the kit, else one named like it (an unpopulated submodule in a fresh
# clone has nothing to read).
OLD="" KNAME=""
mg_modules() { git --no-optional-locks config -f "$1" --get-regexp '^submodule\..*\.path$' 2>/dev/null; }
mg_find_kit() {
    local key path name url mpath="" best="" rank=9 r
    if [[ -f "$WS/.claude/settings.json" ]]; then
        mpath="$(jq -r '.extraKnownMarketplaces["agentic-workspace"].source.path // empty' "$WS/.claude/settings.json" 2>/dev/null)"
        mpath="${mpath#./}"; mpath="${mpath%/}"
    fi
    while read -r key path; do
        [[ -n "$key" ]] || continue
        name="${key#submodule.}"; name="${name%.path}"
        url="$(git --no-optional-locks config -f "$WS/.gitmodules" --get "submodule.$name.url" 2>/dev/null)"
        r=9
        if [[ "$path" == kit ]]; then r=1
        elif [[ -n "$mpath" && "$path" == "$mpath" ]]; then r=2
        elif grep -q '"agentic-workspace"' "$WS/$path/.claude-plugin/marketplace.json" 2>/dev/null; then r=3
        else
            case "$(aw_norm_url "$url")" in */agentic-workspace-kit) r=4 ;; esac
            [[ "${path##*/}" == agentic-workspace ]] && r=4
        fi
        if [[ $r -lt $rank ]]; then rank=$r best="$name	$path"; fi
    done <<EOF
$(mg_modules "$WS/.gitmodules")
EOF
    [[ -n "$best" ]] || return 1
    KNAME="${best%%	*}"; OLD="${best#*	}"
}
mg_find_kit || true
MG_VENDORED=0
[[ -f "$WS/.claude/plugins/VENDORED" ]] && MG_VENDORED=1
if [[ -z "$OLD" && $MG_VENDORED -eq 0 ]]; then
    if [[ -f "$WS/kit/CLAUDE.kit.md" ]]; then
        printf 'migrate: kit/ is here but is not a submodule; this migration expects a kit submodule\n' >&2
    else
        printf 'migrate: no kit checkout here (a submodule of the agentic workspace kit), and no vendored 2.x install\n' >&2
    fi
    exit 1
fi

# The map is read whole before anything runs. A map inside a kit checkout is refused: the kit is
# public, and a map names the workspace's folders.
MAP_LN=() MAP_VERB=() MAP_A=() MAP_B=() MAP_REST=() MAP_DONE=()
mg_map_bad() { printf 'migrate: %s line %s: %s\n' "$MAP" "$1" "$2" >&2; exit 2; }
mg_path_ok() {
    [[ -n "$1" && "$1" != /* ]] || return 1
    case "/$1/" in */../*|*/.git/*) return 1 ;; esac
    return 0
}
mg_norm_path() { local p="$1"; p="${p#./}"; while [[ "$p" == */ ]]; do p="${p%/}"; done; printf '%s' "$p"; }
if [[ -n "$MAP" ]]; then
    [[ -f "$MAP" && -r "$MAP" ]] || { printf 'migrate: cannot read the map %s\n' "$MAP" >&2; exit 2; }
    mg_mapdir="$(cd "$(dirname "$MAP")" && pwd -P)"
    for mg_k in "$MG_SELF_KIT" ${OLD:+"$WS/$OLD"} "$WS/kit"; do
        [[ -d "$mg_k" ]] || continue
        mg_k="$(cd "$mg_k" && pwd -P)"
        case "$mg_mapdir/" in "$mg_k"/*)
            echo "migrate: a map names your folders; keep it outside kit/, which is public" >&2; exit 2 ;;
        esac
    done
    mg_n=0
    while IFS= read -r mg_line || [[ -n "$mg_line" ]]; do
        mg_n=$((mg_n + 1))
        mg_line="${mg_line%$'\r'}"
        mg_t="${mg_line#"${mg_line%%[![:space:]]*}"}"
        [[ -z "$mg_t" || "$mg_t" == \#* ]] && continue
        if [[ "$mg_t" == *$'\t'* ]]; then mg_sep=$'\t'; else mg_sep=' '; fi
        IFS="$mg_sep" read -r -a mg_f <<< "$mg_t"
        mg_verb="${mg_f[0]}"
        mg_rest="${mg_t#"$mg_verb"}"; mg_rest="${mg_rest#"${mg_rest%%[![:space:]]*}"}"
        mg_a="" mg_b="" mg_more=""
        case "$mg_verb" in
            git-mv|submodule-mv|mv|gitignore-rewrite)
                [[ ${#mg_f[@]} -eq 3 ]] || mg_map_bad "$mg_n" "$mg_verb takes two fields"
                mg_a="${mg_f[1]}" mg_b="${mg_f[2]}" ;;
            retire|untrack|gitignore-add|historical)
                [[ ${#mg_f[@]} -eq 2 ]] || mg_map_bad "$mg_n" "$mg_verb takes one field"
                mg_a="${mg_f[1]}" ;;
            rewrite)
                [[ ${#mg_f[@]} -ge 3 ]] || mg_map_bad "$mg_n" "rewrite takes a from, a to, and optional globs"
                mg_a="${mg_f[1]}" mg_b="${mg_f[2]}"
                mg_i=3
                while [[ $mg_i -lt ${#mg_f[@]} ]]; do mg_more+="${mg_more:+	}${mg_f[$mg_i]}"; mg_i=$((mg_i + 1)); done ;;
            submodule-register)
                [[ ${#mg_f[@]} -eq 3 || ${#mg_f[@]} -eq 4 ]] || mg_map_bad "$mg_n" "submodule-register takes a path, a URL and an optional branch"
                mg_a="${mg_f[1]}" mg_b="${mg_f[2]}"; [[ ${#mg_f[@]} -eq 4 ]] && mg_more="${mg_f[3]}" ;;
            header)
                # header <project folder> Versioned=<v> [Sensitivity=<s>]: the README's versioning lines.
                # The pairs are kept in mg_more, tab-separated, Versioned first.
                [[ ${#mg_f[@]} -eq 3 || ${#mg_f[@]} -eq 4 ]] || mg_map_bad "$mg_n" "header takes a project folder and one or two of Versioned=<value> Sensitivity=<value>"
                mg_a="${mg_f[1]}" mg_hv="" mg_hs=""
                mg_i=2
                while [[ $mg_i -lt ${#mg_f[@]} ]]; do
                    case "${mg_f[$mg_i]}" in
                        Versioned=workspace|Versioned=own-repo|Versioned=untracked) [[ -z "$mg_hv" ]] || mg_map_bad "$mg_n" "header names Versioned twice"; mg_hv="${mg_f[$mg_i]}" ;;
                        Sensitivity=normal|Sensitivity=sensitive) [[ -z "$mg_hs" ]] || mg_map_bad "$mg_n" "header names Sensitivity twice"; mg_hs="${mg_f[$mg_i]}" ;;
                        *) mg_map_bad "$mg_n" "header takes Versioned=workspace|own-repo|untracked and Sensitivity=normal|sensitive, not '${mg_f[$mg_i]}'" ;;
                    esac
                    mg_i=$((mg_i + 1))
                done
                mg_more="$mg_hv${mg_hv:+${mg_hs:+	}}$mg_hs" ;;
            keep|note|private-term)
                [[ -n "$mg_rest" ]] || mg_map_bad "$mg_n" "$mg_verb takes text"
                mg_a="$mg_rest"
                if [[ "$mg_verb" == private-term ]]; then
                    printf 'x\n' | grep -E -- "$mg_a" >/dev/null 2>&1; [[ $? -le 1 ]] || mg_map_bad "$mg_n" "private-term takes an extended regex, and this one is not valid"
                fi ;;
            *) mg_map_bad "$mg_n" "unknown verb '$mg_verb'" ;;
        esac
        case "$mg_verb" in
            git-mv|submodule-mv|mv|retire|untrack|submodule-register|header)
                mg_a="$(mg_norm_path "$mg_a")"
                mg_path_ok "$mg_a" || mg_map_bad "$mg_n" "paths are workspace-relative, with no leading / and no .."
                case "$mg_verb" in git-mv|submodule-mv|mv)
                    mg_b="$(mg_norm_path "$mg_b")"
                    mg_path_ok "$mg_b" || mg_map_bad "$mg_n" "paths are workspace-relative, with no leading / and no .." ;;
                esac ;;
            rewrite)
                # A rewrite keeps its text as written: a trailing / is part of what it matches.
                { mg_path_ok "${mg_a#./}" && mg_path_ok "${mg_b#./}"; } \
                    || mg_map_bad "$mg_n" "paths are workspace-relative, with no leading / and no .." ;;
            historical)
                mg_a="$(mg_norm_path "$mg_a")"
                mg_path_ok "$mg_a" || mg_map_bad "$mg_n" "paths are workspace-relative, with no leading / and no .." ;;
        esac
        case "$mg_verb" in
            git-mv|submodule-mv|mv|retire|untrack|header)
                for mg_p in "$mg_a" ${mg_b:+"$mg_b"}; do
                    case "$mg_p" in kit|kit/*) mg_map_bad "$mg_n" "the kit checkout is not moved by a map line" ;; esac
                    if [[ -n "$OLD" ]]; then case "$mg_p" in "$OLD"|"$OLD"/*) mg_map_bad "$mg_n" "the kit checkout is not moved by a map line" ;; esac; fi
                    mg_touches_opaque "$mg_p" && mg_map_bad "$mg_n" "it names an opaque file, which the migration never opens or moves"
                done ;;
            rewrite)
                [[ ${#mg_a} -ge 3 ]] || mg_map_bad "$mg_n" "a rewrite's from is a path of at least 3 characters"
                while IFS= read -r mg_p; do
                    [[ -n "$mg_p" ]] && mg_is_opaque "$mg_p" && mg_map_bad "$mg_n" "it names an opaque file, which the migration never opens or moves"
                done < <(printf '%s\n' "$mg_more" | tr '\t' '\n') ;;
            gitignore-add|gitignore-rewrite)
                case "/$mg_a/$mg_b/" in */../*) mg_map_bad "$mg_n" "a pattern with .. is not a workspace path" ;; esac ;;
        esac
        if [[ "$mg_verb" == submodule-mv ]] && mg_g ls-files -s -- "$mg_a" 2>/dev/null | grep . >/dev/null \
            && ! mg_g ls-files -s -- "$mg_a" | awk -v p="$mg_a" '$1 == "160000" && substr($0, index($0, "\t") + 1) == p { f = 1 } END { exit !f }'; then
            mg_map_bad "$mg_n" "submodule-mv needs a gitlink, and $mg_a is tracked content (git-mv moves it)"
        fi
        MAP_LN+=("$mg_n") MAP_VERB+=("$mg_verb") MAP_A+=("$mg_a") MAP_B+=("$mg_b") MAP_REST+=("$mg_more") MAP_DONE+=(0)
    done < "$MAP"
fi
# The keep literals, one per line, for every rewrite (M7's included), and the historical globs, which
# join the dated records before any step reads them.
MG_KEEP="$MG_TMP/keep"
: > "$MG_KEEP"
mg_i=0
while [[ $mg_i -lt ${#MAP_VERB[@]} ]]; do
    [[ "${MAP_VERB[$mg_i]}" == keep ]] && printf '%s\n' "${MAP_A[$mg_i]}" >> "$MG_KEEP"
    [[ "${MAP_VERB[$mg_i]}" == historical ]] && MG_HIST_GLOBS+=("${MAP_A[$mg_i]}")
    mg_i=$((mg_i + 1))
done

[[ $DRY -eq 1 ]] && echo "Dry run: nothing in the workspace is moved or changed."
echo "Migrating $WS to the kit 3.0 layout."

# The kit to migrate to. --kit-from brings the kit checkout to REF; an unpopulated submodule is
# initialised from URL for this run only, leaving .gitmodules as it is. A dry run changes nothing, the
# kit checkout included: it names the fetch, and reads the kit checkout when that is already 3.0, or
# else this script's own kit (which is 3.0).
MG_DRY_SELF=0
if [[ -n "$KIT_FROM" && -n "$OLD" && $DRY -eq 1 ]]; then
    # The lines the real run would print, worked out without touching the kit checkout: the remote's
    # refs come from ls-remote, which writes nothing. Offline, the fetch and checkout are named anyway.
    mg_proto "$KIT_FROM"
    mg_refs="$(git --no-optional-locks ${MG_PC:+-c "$MG_PC"} ls-remote -- "$KIT_FROM" 2>/dev/null)"
    mg_ref_sha() { printf '%s\n' "$mg_refs" | awk -v r="$1" '$2 == r { print $1; exit }'; }
    mg_want="$(mg_ref_sha "refs/heads/$KIT_REF")"
    [[ -n "$mg_want" ]] || mg_want="$(mg_ref_sha "refs/tags/$KIT_REF^{}")"
    [[ -n "$mg_want" ]] || mg_want="$(mg_ref_sha "refs/tags/$KIT_REF")"
    [[ -n "$mg_want" ]] || mg_want="$(mg_ref_sha "$KIT_REF")"
    [[ -z "$mg_want" && "$KIT_REF" =~ ^[0-9a-f]{7,40}$ ]] && mg_want="$KIT_REF"
    if [[ ! -e "$WS/$OLD/.git" ]]; then
        mg_would run "git submodule init -- $OLD"
        mg_would config "submodule.$KNAME.url=$KIT_FROM"
        mg_would run "git ${MG_PC:+-c $MG_PC }submodule update --remote -- $OLD"
        # submodule update --remote lands on the branch .gitmodules names, else the remote's HEAD.
        mg_br="$(git --no-optional-locks config -f "$WS/.gitmodules" --get "submodule.$KNAME.branch" 2>/dev/null)"
        if [[ -n "$mg_br" ]]; then mg_have="$(mg_ref_sha "refs/heads/$mg_br")"; else mg_have="$(mg_ref_sha HEAD)"; fi
    else
        mg_have="$(aw_git_elsewhere "$WS/$OLD" rev-parse -q --verify HEAD 2>/dev/null)"
    fi
    if [[ -n "$mg_want" && "$mg_have" == "$mg_want" ]]; then
        mg_act skip "kit $OLD is at $KIT_REF already (${mg_want:0:7})"
    else
        mg_would run "git -C $OLD fetch $KIT_FROM $KIT_REF"
        if [[ -n "$mg_want" ]]; then mg_would run "git -C $OLD checkout --detach ${mg_want:0:12}"
        else mg_would run "git -C $OLD checkout --detach FETCH_HEAD"; fi
    fi
    [[ -f "$WS/$OLD/CLAUDE.kit.md" ]] || MG_DRY_SELF=1
elif [[ -n "$KIT_FROM" && -n "$OLD" ]]; then
    mg_kd="$WS/$OLD"
    mg_proto "$KIT_FROM"
    if [[ ! -e "$mg_kd/.git" ]]; then
        mg_do run "git submodule init -- $OLD"
        mg_gw submodule init -q -- "$OLD" >/dev/null 2>&1 || { echo "migrate: git submodule init $OLD failed" >&2; exit 1; }
        mg_do config "submodule.$KNAME.url=$KIT_FROM"
        mg_gw config "submodule.$KNAME.url" "$KIT_FROM" || exit 1
        mg_do run "git ${MG_PC:+-c $MG_PC }submodule update --remote -- $OLD"
        mg_gw ${MG_PC:+-c "$MG_PC"} submodule update -q --remote -- "$OLD" 2>&1 | sed 's/^/    /'
        [[ -e "$mg_kd/.git" ]] || { echo "migrate: the kit checkout at $OLD could not be populated from $KIT_FROM" >&2; exit 1; }
    fi
    if ! aw_git_elsewhere "$mg_kd" ${MG_PC:+-c "$MG_PC"} fetch -q "$KIT_FROM" "$KIT_REF" 2>"$MG_TMP/fetch.err"; then
        printf 'migrate: fetching %s from %s failed: %s\n' "$KIT_REF" "$KIT_FROM" "$(head -n 1 "$MG_TMP/fetch.err")" >&2
        exit 1
    fi
    mg_want="$(aw_git_elsewhere "$mg_kd" rev-parse FETCH_HEAD 2>/dev/null)"
    if [[ "$(aw_git_elsewhere "$mg_kd" rev-parse HEAD 2>/dev/null)" == "$mg_want" ]]; then
        mg_act skip "kit $OLD is at $KIT_REF already (${mg_want:0:7})"
    else
        mg_do run "git -C $OLD fetch $KIT_FROM $KIT_REF"
        mg_do run "git -C $OLD checkout --detach ${mg_want:0:12}"
        (unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE; git -C "$mg_kd" checkout -q --detach "$mg_want") 2>"$MG_TMP/co.err" || {
            printf 'migrate: the kit checkout at %s could not move to %s: %s\n' "$OLD" "$KIT_REF" "$(head -n 1 "$MG_TMP/co.err")" >&2
            printf 'Commit or set aside the changes inside %s first.\n' "$OLD" >&2
            exit 1
        }
    fi
fi
if [[ -n "$OLD" && $MG_DRY_SELF -eq 0 && ! -f "$WS/$OLD/CLAUDE.kit.md" ]]; then
    printf 'migrate: the kit checkout at %s is not the 3.0 kit: advance the kit first (git -C %s pull), or pass --kit-from\n' "$OLD" "$OLD" >&2
    exit 1
fi

# The kit the run reads: the checkout at its old path until M1 moves it (in a dry run it stays
# there), or this script's own kit when there is no checkout yet (M2).
if [[ -n "$OLD" && $MG_DRY_SELF -eq 0 ]]; then MG_KIT="$WS/$OLD"; else MG_KIT="$MG_SELF_KIT"; fi

# ---- The steps -----------------------------------------------------------------------------------

# M0: a kit checkout with a .git folder of its own (made with git clone, then git submodule add) is
# absorbed into the workspace's .git/modules, so git mv can move it.
# The kit's hooks path moves with its .git, so M8 always runs after an absorb.
MG_M0_ACTED=0
if [[ -n "$OLD" && -d "$WS/$OLD/.git" ]]; then
    mg_act run "git submodule absorbgitdirs -- $OLD"
    MG_M0_ACTED=1
    if [[ $DRY -eq 0 ]]; then
        mg_child mg_gw submodule absorbgitdirs -- "$OLD" || mg_stop M0 "git submodule absorbgitdirs $OLD failed"
    fi
else
    mg_act skip "M0 embedded kit .git (none)"
fi

# M0b: gitlinks with no .gitmodules entry. Map lines that register or untrack one run here.
MG_ORPHANS=()
while IFS= read -r mg_gl; do
    [[ -n "$mg_gl" ]] || continue
    if ! mg_modules "$WS/.gitmodules" | awk -v p="$mg_gl" '$2 == p { f = 1 } END { exit !f }'; then MG_ORPHANS+=("$mg_gl"); fi
done < <(mg_g ls-files -s 2>/dev/null | awk '$1 == "160000" { print substr($0, index($0, "\t") + 1) }')

# mg_stage_gitmodules STEP: git refuses to move a submodule while .gitmodules has unstaged changes, so
# every write to it in a real run is staged at once. A dry run prints the same line.
mg_stage_gitmodules() {
    mg_act run "git add .gitmodules (a submodule move needs it staged)"
    [[ $DRY -eq 1 ]] && return 0
    mg_gw add -- .gitmodules || mg_stop "$1" "git add .gitmodules failed"
}

mg_register() {  # PATH URL [BRANCH]
    local p="$1" url="$2" br="${3:-}" gm
    if ! mg_vgitlink "$p"; then mg_act skip "submodule-register $p (not a gitlink here)"; return 0; fi
    gm="$(mg_vphys .gitmodules 2>/dev/null)" || gm=""
    if [[ -n "$gm" ]] && mg_modules "$gm" | awk -v p="$p" '$2 == p { f = 1 } END { exit !f }'; then
        mg_act skip "submodule-register $p (registered already)"; return 0
    fi
    if [[ $DRY -eq 1 ]]; then
        [[ -e "$SHADOW/.gitmodules" ]] || { if [[ -f "$WS/.gitmodules" ]]; then cat "$WS/.gitmodules"; fi; } | mg_vwrite .gitmodules
        gm="$SHADOW/.gitmodules"
    else
        gm="$WS/.gitmodules"
    fi
    mg_act config ".gitmodules submodule.$p.path=$p"
    git config -f "$gm" "submodule.$p.path" "$p" || mg_stop M0b "writing .gitmodules failed"
    mg_act config ".gitmodules submodule.$p.url=$url"
    git config -f "$gm" "submodule.$p.url" "$url" || mg_stop M0b "writing .gitmodules failed"
    if [[ -n "$br" ]]; then
        mg_act config ".gitmodules submodule.$p.branch=$br"
        git config -f "$gm" "submodule.$p.branch" "$br" || mg_stop M0b "writing .gitmodules failed"
    fi
    mg_stage_gitmodules submodule-register
    mg_plan .gitmodules
}
mg_untrack() {  # PATH
    local p="$1"
    if mg_vtracked "$p"; then
        mg_act run "git rm -r --cached -q -- $p (the files stay on disk)"
        if [[ $DRY -eq 1 ]]; then mg_op "U	$p"; else mg_gw rm -r --cached -q -- "$p" || mg_stop "untrack" "git rm --cached $p failed"; fi
        MG_STAGED+=("$p")
    elif mg_vexists "$p"; then
        mg_act skip "untrack $p (not tracked)"
    else
        mg_act skip "untrack $p (not present here)"
    fi
    if mg_ignore_has "/$p" || mg_ignore_has "/$p/"; then
        mg_act skip "untrack $p (.gitignore lists /$p already)"
    else
        mg_act edit ".gitignore: + /$p"
        mg_ignore_add "/$p"
    fi
}

# mg_vignored PATH: 0 when the .gitignore this run has written so far ignores PATH. A dry run reads its
# edited copy too (as core.excludesFile), since the real file is not changed yet. A folder is named
# with a trailing /, because one a dry run has only pretended to move is not on disk for git to see.
mg_vignored() {
    local p="$1" ph
    ph="$(mg_vphys "$p" 2>/dev/null)" && [[ -d "$ph" ]] && p="$p/"
    if [[ $DRY -eq 1 && -f "$SHADOW/.gitignore" ]]; then
        mg_g -c core.excludesFile="$SHADOW/.gitignore" check-ignore -q --no-index -- "$p" 2>/dev/null
    else
        mg_g check-ignore -q --no-index -- "$p" 2>/dev/null
    fi
}

# mg_header DIR PAIRS: the versioning lines of DIR/README.md, from PAIRS (Label=value, tab-separated).
# A line that is there with another value is rewritten; a missing one is written as "- **Label:**
# value", beside the other versioning line when there is one, else directly under the title.
mg_header() {
    local dir="$1" rd="$1/README.md" kv lab val ph scan n cur title other at out="$MG_TMP/header" changed=0
    if ! mg_vexists "$rd"; then mg_act skip "header $dir (no README.md here)"; return 0; fi
    for kv in $(printf '%s' "$2" | tr '\t' ' '); do
        lab="${kv%%=*}" val="${kv#*=}"
        ph="$(mg_vphys "$rd")" || return 0
        # One pass: "L n value" for this label's first line, "O n" for the other label's, "T n" for the
        # title, all outside fences and HTML comments; labels match bold or plain, in any case.
        scan="$(awk -v lab="$(printf '%s' "$lab" | tr '[:upper:]' '[:lower:]')" '
            BEGIN { oth = (lab == "versioned") ? "sensitivity" : "versioned" }
            /^[ \t]*(```|~~~)/ { fence = !fence; next }
            fence { next }
            /<!--/ { com = 1 } com { if (/-->/) com = 0; next }
            !t && /^# / { print "T " NR; t = 1; next }
            {
                l = tolower($0); sub(/^[ \t]*([-*+][ \t]+)?/, "", l); gsub(/\*\*|__/, "", l)
                if (!f && index(l, lab ":") == 1) {
                    v = substr(l, length(lab) + 2); sub(/^[ \t]+/, "", v); sub(/[ \t].*$/, "", v); gsub(/[`*_.,;]/, "", v)
                    print "L " NR " " v; f = 1
                } else if (!o && index(l, oth ":") == 1) { print "O " NR; o = 1 }
            }' "$ph")"
        n="$(printf '%s\n' "$scan" | awk '$1 == "L" { print $2 }')"
        cur="$(printf '%s\n' "$scan" | awk '$1 == "L" { print $3 }')"
        title="$(printf '%s\n' "$scan" | awk '$1 == "T" { print $2 }')"
        other="$(printf '%s\n' "$scan" | awk '$1 == "O" { print $2 }')"
        if [[ -n "$n" && "$cur" == "$val" ]]; then
            mg_act skip "header $rd $lab: $val (there already)"
            continue
        fi
        if [[ -n "$n" ]]; then
            mg_act edit "$rd:$n $lab: ${cur:-(empty)} -> $val"
            awk -v n="$n" -v lab="$lab" -v val="$val" 'NR == n { print "- **" lab ":** " val; next } { print }' "$ph" > "$out"
        else
            # Versioned goes above a Sensitivity line, Sensitivity below a Versioned one.
            if [[ -n "$other" && "$lab" == Versioned ]]; then at=$((other - 1))
            elif [[ -n "$other" ]]; then at="$other"
            else at="${title:-0}"; fi
            if [[ -n "$other" ]]; then
                mg_act edit "$rd:$((at + 1)) + $lab: $val"
                awk -v at="$at" -v nl="- **$lab:** $val" 'at == 0 && NR == 1 { print nl } { print } NR == at { print nl }' "$ph" > "$out"
            else
                # Under the title, with a blank line either side; a blank line already there is reused.
                if [[ "$at" -gt 0 ]]; then mg_act edit "$rd:$((at + 2)) + $lab: $val"; else mg_act edit "$rd:1 + $lab: $val"; fi
                awk -v at="$at" -v nl="- **$lab:** $val" '
                    { L[NR] = $0 }
                    END {
                        for (i = 1; i <= at; i++) print L[i]
                        i = at + 1
                        if (at > 0) { if (i <= NR && L[i] ~ /^[ \t]*$/) { print L[i]; i++ } else print "" }
                        print nl
                        if (i <= NR && L[i] !~ /^[ \t]*$/) print ""
                        for (; i <= NR; i++) print L[i]
                    }' "$ph" > "$out"
            fi
        fi
        mg_vwrite "$rd" < "$out"
        changed=1
    done
    if [[ $changed -eq 1 ]]; then MG_EDITED+=("$rd"); mg_plan "$rd"; fi
    case "$2" in *Versioned=untracked*)
        mg_vignored "$dir" || mg_act note "$dir is Versioned: untracked and .gitignore does not list it yet: a gitignore-add /$dir/ line before this one keeps it out of the repository" ;;
    esac
    case "$2" in *Sensitivity=sensitive*)
        if mg_vtracked "$dir" && ! mg_vignored "$dir"; then
            mg_act note "$dir is sensitive and tracked by the workspace, whose hooks refuse its files: an untrack $dir line keeps it on disk and out of the repository"
        fi ;;
    esac
    return 0
}

mg_resolved=0
mg_i=0
while [[ $mg_i -lt ${#MAP_VERB[@]} ]]; do
    case "${MAP_VERB[$mg_i]}" in submodule-register|untrack)
        for mg_o in ${MG_ORPHANS[@]+"${MG_ORPHANS[@]}"}; do
            [[ "$mg_o" == "${MAP_A[$mg_i]}" ]] || continue
            if [[ "${MAP_VERB[$mg_i]}" == submodule-register ]]; then
                mg_register "${MAP_A[$mg_i]}" "${MAP_B[$mg_i]}" "${MAP_REST[$mg_i]}"
            else
                mg_untrack "${MAP_A[$mg_i]}"
            fi
            MAP_DONE[mg_i]=1; mg_resolved=1
        done ;;
    esac
    mg_i=$((mg_i + 1))
done
mg_left=()
for mg_o in ${MG_ORPHANS[@]+"${MG_ORPHANS[@]}"}; do
    mg_fixed=0 mg_i=0
    while [[ $mg_i -lt ${#MAP_VERB[@]} ]]; do
        [[ "${MAP_DONE[$mg_i]}" == 1 && "${MAP_A[$mg_i]}" == "$mg_o" ]] && mg_fixed=1
        mg_i=$((mg_i + 1))
    done
    [[ $mg_fixed -eq 1 ]] || mg_left+=("$mg_o")
done
if [[ ${#MG_ORPHANS[@]} -eq 0 ]]; then
    mg_act skip "M0b orphan gitlinks (none)"
elif [[ $mg_resolved -eq 0 ]]; then
    mg_act skip "M0b orphan gitlinks (no map line resolves ${MG_ORPHANS[*]})"
fi

# M1: the kit checkout moves to kit/. The submodule keeps its name; .gitmodules gains branch=main.
if [[ -n "$OLD" && "$OLD" != kit ]]; then
    if mg_vexists kit; then mg_stop M1 "kit/ exists and is not the kit submodule; move it aside and run again"; fi
    mg_move M1 "$OLD" kit "git mv"
    mg_plan .gitmodules; mg_plan kit
    [[ $DRY -eq 0 ]] && MG_KIT="$WS/kit"
    MG_OLD_KIT_PATH="$OLD"
else
    MG_OLD_KIT_PATH=""
    if [[ -n "$OLD" ]]; then mg_act skip "M1 kit at kit/ (already there)"
    else mg_act skip "M1 kit at kit/ (no kit checkout yet; M2 adds one)"; fi
fi
if [[ -n "$KNAME" ]]; then
    mg_gm="$(mg_vphys .gitmodules 2>/dev/null)" || mg_gm=""
    if [[ -n "$mg_gm" ]] && [[ -z "$(git --no-optional-locks config -f "$mg_gm" --get "submodule.$KNAME.branch" 2>/dev/null)" ]]; then
        mg_act config ".gitmodules submodule.$KNAME.branch=main"
        if [[ $DRY -eq 1 ]]; then
            [[ -e "$SHADOW/.gitmodules" ]] || cat "$WS/.gitmodules" | mg_vwrite .gitmodules
            git config -f "$SHADOW/.gitmodules" "submodule.$KNAME.branch" main
        else
            git config -f "$WS/.gitmodules" "submodule.$KNAME.branch" main || mg_stop M1 "writing .gitmodules failed"
        fi
        mg_stage_gitmodules M1
        mg_plan .gitmodules
    fi
fi

# M2: a vendored 2.x install with no kit submodule gets one at kit/.
if [[ -z "$OLD" && $MG_VENDORED -eq 1 ]]; then
    mg_url="$KIT_FROM"
    [[ -n "$mg_url" ]] || mg_url="$(git --no-optional-locks -C "$MG_SELF_KIT" remote get-url origin 2>/dev/null)"
    [[ -n "$mg_url" ]] || mg_url="$MG_DEFAULT_URL"
    mg_proto "$mg_url"
    mg_act run "git ${MG_PC:+-c $MG_PC }submodule add -b main $mg_url kit"
    if [[ $DRY -eq 0 ]]; then
        mg_child mg_gw ${MG_PC:+-c "$MG_PC"} submodule add -q -b main "$mg_url" kit || mg_stop M2 "git submodule add $mg_url kit failed"
        if [[ "$KIT_REF" != main ]]; then
            mg_act run "git -C kit checkout --detach $KIT_REF"
            if ! { aw_git_elsewhere "$WS/kit" ${MG_PC:+-c "$MG_PC"} fetch -q "$mg_url" "$KIT_REF" \
                && (unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE; git -C "$WS/kit" checkout -q --detach FETCH_HEAD); }; then
                mg_stop M2 "checking out $KIT_REF in kit/ failed"
            fi
        fi
        MG_KIT="$WS/kit"
        [[ -f "$MG_KIT/CLAUDE.kit.md" ]] || mg_stop M2 "the kit added from $mg_url is not the 3.0 kit (no CLAUDE.kit.md)"
        KNAME="$(aw_kitname "$WS")"
    fi
    mg_plan .gitmodules; mg_plan kit
else
    mg_act skip "M2 vendored install without a kit submodule (not this workspace)"
fi

# M3: the plugin marketplace is the kit checkout, at kit. Only that key of the settings changes.
MG_SOURCE='{"source":"directory","path":"kit"}'
if mg_vexists .claude/settings.json; then
    mg_cur="$(mg_vread .claude/settings.json | jq -c -S '.extraKnownMarketplaces["agentic-workspace"].source // null' 2>/dev/null)"
    if [[ -z "$mg_cur" ]]; then
        mg_stop M3 ".claude/settings.json is not valid JSON; fix it and run again"
    elif [[ "$mg_cur" == "$(printf '%s' "$MG_SOURCE" | jq -c -S .)" ]]; then
        mg_act skip "M3 marketplace path (kit already)"
    else
        mg_act edit ".claude/settings.json extraKnownMarketplaces.agentic-workspace.source: $mg_cur -> $MG_SOURCE"
        mg_vread .claude/settings.json | jq --argjson s "$MG_SOURCE" '.extraKnownMarketplaces["agentic-workspace"].source = $s' > "$MG_TMP/settings.json" \
            || mg_stop M3 "editing .claude/settings.json failed"
        mg_vwrite .claude/settings.json < "$MG_TMP/settings.json"
        mg_plan .claude/settings.json; MG_EDITED+=(.claude/settings.json)
    fi
else
    mg_act skip "M3 marketplace path (no .claude/settings.json; the engine creates one at M15)"
fi

# M4: the vendored plugins are retired; the plugins are read from kit/ now.
if mg_vexists .claude/plugins; then mg_retire M4 .claude/plugins; else mg_act skip "M4 vendored plugins (none)"; fi

# M5: skills the 2.x installer generated leave skills/ (and the old mirror in .claude/skills/). A
# skill without the generator's marker is the team's own, and stays. A folder the 3.0 skills bridge
# lists in .claude/skills/.kit-generated is the bridge's, and stays too.
mg_gen=0
mg_bridged=""
if mg_vexists .claude/skills/.kit-generated; then
    mg_bridged="$(mg_vread .claude/skills/.kit-generated | awk -F '\t' '!/^#/ && NF >= 2 { print $2 }')"
fi
for mg_dir in skills .claude/skills; do
    mg_vexists "$mg_dir" || continue
    for mg_s in "$WS/$mg_dir"/*/; do
        [[ -d "$mg_s" ]] || continue
        mg_s="${mg_s%/}"; mg_s="$mg_dir/${mg_s##*/}"
        mg_vexists "$mg_s/SKILL.md" || continue
        if [[ "$mg_dir" == .claude/skills && -n "$mg_bridged" ]] \
            && printf '%s\n' "$mg_bridged" | grep -Fx -- "${mg_s##*/}" >/dev/null; then
            continue
        fi
        if mg_vread "$mg_s/SKILL.md" | grep -F "$MG_MARKER" >/dev/null; then
            mg_gen=1
            mg_retire M5 "$mg_s"
        fi
    done
done
[[ $mg_gen -eq 1 ]] || mg_act skip "M5 generated skills (none)"

# M6: unchanged 2.x copies of kit-owned files. A copy whose blob matches the kit's file at any commit
# is retired, and the conventions that named it point at kit/<path>. A copy that differs is the
# team's now, and stays.
MG_LEDGER=0
mg_vexists .claude/kit-templates.lock && MG_LEDGER=1
mg_kit_blobs() {  # the blob shas the kit has held at PATH
    aw_git_elsewhere "$MG_KIT" log --all --format= --raw --no-abbrev --no-renames -- "$1" 2>/dev/null | awk '{ print $4 }'
    aw_git_elsewhere "$MG_KIT" rev-parse -q --verify "HEAD:$1" 2>/dev/null
}
mg_m6_paths=(docs/memory-layers.md docs/documentation-register.md docs/images/context-taxonomy.svg)
for mg_s in "$WS"/rituals/*.md; do [[ -f "$mg_s" ]] && mg_m6_paths+=("rituals/${mg_s##*/}"); done
mg_m6_paths+=(templates/project-readme.md templates/project-decisions.md templates/person-profile.md
    templates/catalogue.md templates/team-roster.md templates/verification-standard.md pilot/README.md pilot/measure.sh)
mg_m6_any=0 mg_m6_differs=""
for mg_p in "${mg_m6_paths[@]}"; do
    mg_vexists "$mg_p" || continue
    mg_is_opaque "$mg_p" && continue
    mg_ph="$(mg_vphys "$mg_p")" || continue
    [[ -f "$mg_ph" ]] || continue
    mg_blob="$(git hash-object -- "$mg_ph" 2>/dev/null)"
    if mg_kit_blobs "$mg_p" | grep -xF "$mg_blob" >/dev/null; then
        mg_m6_any=1
        mg_retire M6 "$mg_p"
        for mg_conv in .claude/projects.md .claude/closeout.md; do
            mg_vexists "$mg_conv" && mg_rewrite_in "$mg_conv" "$mg_p" "kit/$mg_p" word
        done
    else
        mg_m6_differs+="${mg_m6_differs:+, }$mg_p"
        if [[ $MG_LEDGER -eq 0 ]]; then
            mg_m6_any=1
            mg_act note "$mg_p differs from the kit's copy: yours now; the kit's is kit/$mg_p"
            mg_act note "  map line that would point the conventions at the kit's copy: rewrite $mg_p kit/$mg_p .claude/projects.md .claude/closeout.md"
        fi
    fi
done
if [[ $mg_m6_any -eq 0 ]]; then
    if [[ -n "$mg_m6_differs" ]]; then mg_act skip "M6 unchanged copies of kit files (none; yours, differing from the kit's: $mg_m6_differs)"
    else mg_act skip "M6 unchanged copies of kit files (none)"; fi
fi

# M7: references to the old kit path, outside the kit, opaque files and dated records (the map's
# historical lines included), now name kit/. An occurrence inside a map's keep literal stays.
if [[ -n "$MG_OLD_KIT_PATH" ]]; then
    mg_from="$MG_OLD_KIT_PATH/"
    mg_hist=() mg_edit=()
    while IFS=$'\t' read -r mg_vp mg_ph; do
        [[ -n "$mg_vp" ]] || continue
        if mg_is_historical "$mg_vp"; then mg_hist+=("$mg_vp"); else mg_edit+=("$mg_vp"); fi
    done < <(mg_candidates "$mg_from" ext)
    # A file whose only occurrences are kept literals is a candidate that M7 leaves as it is.
    mg_before=${#MG_EDITED[@]}
    for mg_vp in ${mg_edit[@]+"${mg_edit[@]}"}; do mg_rewrite_in "$mg_vp" "$mg_from" "kit/" any "$MG_KEEP"; done
    mg_m7_did=0; [[ ${#MG_EDITED[@]} -gt $mg_before ]] && mg_m7_did=1
    if [[ $mg_m7_did -eq 1 || $MG_LEDGER -eq 0 ]]; then
        for mg_vp in ${mg_hist[@]+"${mg_hist[@]}"}; do
            for mg_n in $(mg_replace "$(mg_vphys "$mg_vp")" "" "$mg_from" "kit/" any "$MG_KEEP"); do
                mg_act note "$mg_vp:$mg_n names $mg_from (a dated record keeps its wording)"
            done
        done
    fi
    if [[ $mg_m7_did -eq 0 && ( ${#mg_hist[@]} -eq 0 || $MG_LEDGER -eq 1 ) ]]; then
        mg_act skip "M7 references to $mg_from (none left${mg_hist[0]:+; ${#mg_hist[@]} dated records keep theirs})"
    fi
else
    mg_act skip "M7 references to the old kit path (the kit was at kit/ already)"
fi

# Orphan gitlinks break git's submodule walks, so the run stops here, before the hooks and submodule
# settings, while any remains.
if [[ ${#mg_left[@]} -gt 0 ]]; then
    for mg_o in "${mg_left[@]}"; do
        printf 'migrate: %s is a gitlink with no .gitmodules entry. Add one of these lines to the map and run again:\n' "$mg_o" >&2
        printf '  submodule-register %s <url> [<branch>]    to make it a submodule\n' "$mg_o" >&2
        printf '  untrack %s    to keep it as a local repository that the workspace ignores\n' "$mg_o" >&2
    done
    mg_stop "the orphan gitlink check (before M8)" "${#mg_left[@]} orphan gitlink(s): ${mg_left[*]}"
fi

# The state check, from the kit being migrated to, for M8 and M9.
MG_STATE=""
mg_state() {
    [[ -n "$MG_STATE" ]] && return 0
    MG_STATE="$(bash "$MG_KIT/plugins/workspace/bin/state.sh" --target "$WS" 2>/dev/null)" || MG_STATE=""
    [[ -n "$MG_STATE" ]] || MG_STATE="state_version=unknown"
}
mg_key() { printf '%s\n' "$MG_STATE" | awk -v k="$1=" 'index($0, k) == 1 { print substr($0, length(k) + 1); f = 1; exit } END { if (!f) print "\001" }'; }

# M8: the git hooks. gitconfig.sh keeps any hooks path already in effect as aw.chainHooksPath, so a
# hook of the person's own still runs after the kit's.
mg_state
mg_h="$(mg_key hooks)" mg_kh="$(mg_key kit_hooks)"
if [[ "$mg_h" == $'\001' ]]; then
    bash "$MG_KIT/lib/setup/gitconfig.sh" --target "$WS" --hooks --check >/dev/null 2>&1 && mg_h=active mg_kh=active
fi
if [[ $MG_M0_ACTED -eq 0 && "$mg_h" == active && ( "$mg_kh" == active || "$mg_kh" == $'\001' ) ]]; then
    mg_act skip "M8 hooks (active)"
else
    mg_act run "kit/lib/setup/gitconfig.sh --target $WS --hooks"
    if [[ $DRY -eq 0 ]]; then
        mg_child bash "$WS/kit/lib/setup/gitconfig.sh" --target "$WS" --hooks || mg_stop M8 "kit/lib/setup/gitconfig.sh --hooks failed"
    elif [[ -n "$KIT_FROM" && -n "$OLD" && ! -e "$WS/$OLD/.git" ]]; then
        # The kit checkout is populated only by the real run, so its hooks are named, not read.
        mg_preview bash "$MG_KIT/lib/setup/gitconfig.sh" --target "$WS" --hooks --check --kit-at "$OLD" \
            | sed 's/^    skip kit (not initialised.*/    would set kit aw-hooks, aw.chainHooksPath (when a hooks path is in effect there) and core.hooksPath, once --kit-from has populated it/'
    elif [[ $MG_M0_ACTED -eq 1 ]]; then
        # M0 has not absorbed the kit's .git in a dry run, so gitconfig.sh sees the folder inside the
        # checkout. The real run's M8 finds it where absorbgitdirs puts it, under the workspace's
        # .git/modules/<submodule name>, and the kit's hooks path is named as it will be there.
        mg_kgd_old="$WS/$OLD/.git/aw-hooks"
        mg_kgd_new="$(mg_g rev-parse --absolute-git-dir 2>/dev/null)/modules/$KNAME/aw-hooks"
        mg_preview bash "$MG_KIT/lib/setup/gitconfig.sh" --target "$WS" --hooks --check --kit-at "$OLD" \
            | awk -v from="$mg_kgd_old" -v to="$mg_kgd_new" '{
                while ((i = index($0, from)) > 0) $0 = substr($0, 1, i - 1) to substr($0, i + length(from))
                if ($0 == "    ok kit core.hooksPath") $0 = "    would set kit core.hooksPath=" to
                print }'
    else
        mg_preview bash "$MG_KIT/lib/setup/gitconfig.sh" --target "$WS" --hooks --check ${OLD:+--kit-at "$OLD"}
    fi
fi

# M9: submodule settings (held submodule.recurse is gitconfig.sh's call).
mg_sc="$(mg_key submodule_config)"
if [[ "$mg_sc" == $'\001' ]]; then
    bash "$MG_KIT/lib/setup/gitconfig.sh" --target "$WS" --submodules --check >/dev/null 2>&1 && mg_sc=ok
fi
if [[ "$mg_sc" == ok ]]; then
    mg_act skip "M9 submodule settings (ok)"
else
    mg_act run "kit/lib/setup/gitconfig.sh --target $WS --submodules"
    if [[ $DRY -eq 0 ]]; then
        mg_child bash "$WS/kit/lib/setup/gitconfig.sh" --target "$WS" --submodules || mg_stop M9 "kit/lib/setup/gitconfig.sh --submodules failed"
    else
        mg_preview bash "$MG_KIT/lib/setup/gitconfig.sh" --target "$WS" --submodules --check ${OLD:+--kit-at "$OLD"}
    fi
fi

# M10: the template's .gitignore lines that are missing, appended under the kit's header. Lines the
# person declined at an update (the ledger's !declined lines) stay out.
mg_tpl="$MG_KIT/templates/workspace.gitignore"
if [[ ! -f "$mg_tpl" ]]; then
    mg_act skip "M10 .gitignore (this kit has no templates/workspace.gitignore)"
else
    mg_declined="$MG_TMP/declined"
    mg_vread .claude/kit-templates.lock 2>/dev/null | awk -F '\t' '$1 == "!declined" && $2 == ".gitignore" { print $3 }' > "$mg_declined"
    mg_added=0
    # Only spaces and tabs are trimmed: a carriage return can be part of a pattern (macOS names its
    # folder-icon file Icon followed by one, and the template's line ends in two, since git drops one).
    mg_blank=$' \t'
    while IFS= read -r mg_l || [[ -n "$mg_l" ]]; do
        mg_l="${mg_l%"${mg_l##*[!"$mg_blank"]}"}"
        [[ -z "$mg_l" || "$mg_l" == \#* ]] && continue
        mg_ignore_has "$mg_l" && continue
        grep -qxF -- "$mg_l" "$mg_declined" && continue
        mg_act edit ".gitignore: + ${mg_l//$'\r'/\\r}"
        mg_ignore_add "$mg_l" kit
        mg_added=1
    done < "$mg_tpl"
    [[ $mg_added -eq 1 ]] || mg_act skip "M10 .gitignore (every template line is there)"
fi

# The project conventions, read through the overlay.
mg_conv_root="$WS"
[[ $DRY -eq 1 && -f "$SHADOW/.claude/projects.md" ]] && mg_conv_root="$SHADOW"
MG_HAVE_CONV=0
if [[ -f "$mg_conv_root/.claude/projects.md" ]] && . "$MG_KIT/plugins/projects/hooks/lib/config.sh" 2>/dev/null \
    && declare -F projects_config >/dev/null; then
    projects_config "$mg_conv_root"
    MG_HAVE_CONV=1
fi
# mg_bullet_text LABEL: the 3.0 bullet, from the kit's template when it has the 3.0 wording.
# The backticks below are Markdown, written literally.
# shellcheck disable=SC2016
mg_bullet_text() {
    local label="$1" t="$MG_KIT/templates/workspace/projects.md" txt=""
    if [[ -f "$t" ]]; then
        txt="$(awk -v lab="**$label:**" '
            /^[ \t]*[-*][ \t]+/ { if (on) exit; if (index($0, lab)) { on = 1; print; next } }
            on && /^[ \t]+[^ \t]/ { print; next }
            on { exit }' "$t")"
    fi
    case "$label" in
        Done)   [[ "$txt" == *'`projects/_done/<slug>/`'* ]] && { printf '%s\n' "$txt"; return; }
                printf '%s\n' '- **Done:** `projects/_done/<slug>/` — `/projects:close` moves the folder here, keeping history: `git mv`' \
                    '  for a project tracked by the workspace or its own repository, and a plain move plus a `.gitignore`' \
                    '  line for an untracked one.' ;;
        Paused) [[ "$txt" == *'/projects:hold'* ]] && { printf '%s\n' "$txt"; return; }
                printf '%s\n' '- **Paused:** `projects/<slug>/` — the folder stays where it is and stays versioned; its register row' \
                    '  moves to the Paused section (`/projects:hold`).' ;;
    esac
}
# mg_edit_bullet LABEL NEWVALUE: replaces the bullet (with its continuation lines) in the conventions.
mg_edit_bullet() {
    local label="$1" newv="$2" ph n out="$MG_TMP/conv"
    ph="$(mg_vphys .claude/projects.md)" || return 0
    mg_bullet_text "$label" > "$MG_TMP/bullet"
    n="$(awk -v lab="**$label:**" -v nb="$MG_TMP/bullet" -v out="$out" '
        BEGIN { while ((getline l < nb) > 0) B[++nb_n] = l }
        skip && /^[ \t]+[^ \t]/ && !/^[ \t]*[-*][ \t]+/ { next }
        { skip = 0 }
        !done && /^[ \t]*[-*][ \t]+/ && index($0, lab) {
            for (i = 1; i <= nb_n; i++) print B[i] > out
            done = 1; skip = 1; print NR; next
        }
        { print > out }' "$ph")"
    if [[ -z "$n" ]]; then mg_act skip "$label: setting (.claude/projects.md has none)"; return 0; fi
    mg_act edit ".claude/projects.md:$n $label: -> \`$newv\`"
    mg_vwrite .claude/projects.md < "$out"
    mg_plan .claude/projects.md; MG_EDITED+=(.claude/projects.md)
}
mg_pattern_dir() { local d="${1%%<*}"; d="${d%/}"; printf '%s' "$d"; }

# M11: finished projects kept in a folder of their own move to projects/_done/.
if [[ $MG_HAVE_CONV -eq 0 ]]; then
    mg_act skip "M11 finished projects (no .claude/projects.md)"
else
    mg_active_dir="$(mg_pattern_dir "$ACTIVE_PATTERN")"
    mg_done_dir="$(mg_pattern_dir "${DONE_PATTERN:-$ACTIVE_PATTERN}")"
    if [[ "$DONE_PATTERN" == "projects/_done/<slug>" ]]; then
        mg_act skip "M11 finished projects (Done: is projects/_done/<slug>/ already)"
    elif [[ -z "$DONE_PATTERN" || "$mg_done_dir" == "$mg_active_dir" ]]; then
        mg_edit_bullet Done 'projects/_done/<slug>/'
    else
        for mg_s in "$WS/$mg_done_dir"/*/; do
            [[ -d "$mg_s" ]] || continue
            mg_s="${mg_s%/}"; mg_s="${mg_s##*/}"
            case "$mg_s" in .*|_*) continue ;; esac
            mg_from="$mg_done_dir/$mg_s" mg_to="projects/_done/$mg_s"
            mg_vexists "$mg_from" || continue
            if mg_touches_opaque "$mg_from"; then mg_act skip "M11 $mg_from (holds an opaque file: left as it is)"; continue; fi
            if mg_vexists "$mg_to"; then mg_act skip "M11 $mg_from -> $mg_to (destination exists)"; continue; fi
            if mg_vtracked "$mg_from"; then
                mg_move M11 "$mg_from" "$mg_to" "git mv"
            else
                mg_by="$(mg_ignored_by "$mg_from/")"
                if [[ -n "$mg_by" ]] && ! mg_ignore_has "/$mg_to/"; then
                    mg_act edit ".gitignore: + /$mg_to/ (kept out of the repository, as $mg_from was by $mg_by)"
                    mg_ignore_add "/$mg_to/"
                fi
                mg_move M11 "$mg_from" "$mg_to" "mv"
            fi
        done
        mg_edit_bullet Done 'projects/_done/<slug>/'
        # The register's links to the old folder: relative to the register, and from the root.
        mg_reg="${REGISTER_FILE:-projects/INDEX.md}"
        if mg_vexists "$mg_reg"; then
            mg_regdir="$(dirname "$mg_reg")"
            if [[ "$mg_regdir" == . ]]; then
                mg_rel_old="$mg_done_dir/" mg_rel_new="projects/_done/"
            else
                mg_up="" mg_rest="$mg_regdir"
                while [[ -n "$mg_rest" ]]; do
                    mg_up+="../"
                    if [[ "$mg_rest" == */* ]]; then mg_rest="${mg_rest%/*}"; else mg_rest=""; fi
                done
                case "$mg_done_dir/" in "$mg_regdir"/*) mg_rel_old="${mg_done_dir#"$mg_regdir"/}/" ;; *) mg_rel_old="$mg_up$mg_done_dir/" ;; esac
                mg_rel_new="projects/_done/"
                case "$mg_rel_new" in "$mg_regdir"/*) mg_rel_new="${mg_rel_new#"$mg_regdir"/}" ;; *) mg_rel_new="$mg_up$mg_rel_new" ;; esac
            fi
            mg_rewrite_in "$mg_reg" "$mg_rel_old" "$mg_rel_new" word
            [[ "$mg_rel_old" != "$mg_done_dir/" ]] && mg_rewrite_in "$mg_reg" "$mg_done_dir/" "projects/_done/" word
        fi
        # .gitignore lines naming the old folder, with the map line that would carry them over.
        mg_n=0
        while IFS= read -r mg_l || [[ -n "$mg_l" ]]; do
            mg_n=$((mg_n + 1))
            case "$mg_l" in "$mg_done_dir"/*|"!$mg_done_dir"/*|"/$mg_done_dir"/*|"!/$mg_done_dir"/*)
                mg_act note ".gitignore:$mg_n $mg_l names $mg_done_dir/; the map line gitignore-rewrite $mg_done_dir/ projects/_done/ carries it over" ;;
            esac
        done < <(mg_vread .gitignore 2>/dev/null)
    fi
fi

# M12: paused projects stay in place from 3.0 on; the conventions say so. Nothing is moved here.
if [[ $MG_HAVE_CONV -eq 0 ]]; then
    mg_act skip "M12 paused projects (no .claude/projects.md)"
else
    mg_paused_dir="$(mg_pattern_dir "${PAUSED_PATTERN:-$ACTIVE_PATTERN}")"
    if [[ -z "$PAUSED_PATTERN" || "$mg_paused_dir" == "$(mg_pattern_dir "$ACTIVE_PATTERN")" ]]; then
        mg_act skip "M12 paused projects (they stay in place already)"
    else
        mg_edit_bullet Paused 'projects/<slug>/'
        mg_cnt=0
        for mg_s in "$WS/$mg_paused_dir"/*/; do [[ -d "$mg_s" ]] && mg_cnt=$((mg_cnt + 1)); done
        if [[ $mg_cnt -gt 0 ]]; then
            mg_act note "$mg_cnt paused projects in $mg_paused_dir/: review each for sensitivity, move them with the map file, then /projects:hold"
        fi
    fi
fi

# M13: CLAUDE.md imports the kit's working standards on its first line, with a prose fallback for a
# surface that does not expand imports.
mg_l1="$MG_IMPORT" mg_l2="$MG_FALLBACK"
if [[ -f "$MG_KIT/templates/workspace/CLAUDE.md" && "$(head -n 1 "$MG_KIT/templates/workspace/CLAUDE.md")" == "$MG_IMPORT" ]]; then
    mg_l2="$(sed -n 2p "$MG_KIT/templates/workspace/CLAUDE.md")"
    [[ -n "$mg_l2" ]] || mg_l2="$MG_FALLBACK"
fi
if mg_is_opaque CLAUDE.md; then
    mg_act skip "M13 CLAUDE.md import (CLAUDE.md is opaque here)"
elif ! mg_vexists CLAUDE.md; then
    mg_act skip "M13 CLAUDE.md import (no CLAUDE.md; the engine creates one at M15)"
else
    mg_first="$(mg_vread CLAUDE.md | awk 'NF { sub(/^[ \t]+/, ""); sub(/[ \t\r]+$/, ""); print; exit }')"
    if [[ "$mg_first" == "$MG_IMPORT" ]]; then
        mg_act skip "M13 CLAUDE.md import (line 1 imports the kit)"
    else
        mg_shim="$(mg_vread CLAUDE.md | awk '
            /<!--/ { c = 1 } c { if (/-->/) c = 0; next }
            NF { sub(/^[ \t]+/, ""); sub(/[ \t\r]+$/, ""); print }')"
        mg_act edit "CLAUDE.md: lines 1-2 $MG_IMPORT and the fallback line"
        { printf '%s\n%s\n\n' "$mg_l1" "$mg_l2"; mg_vread CLAUDE.md; } > "$MG_TMP/claude.md"
        mg_vwrite CLAUDE.md < "$MG_TMP/claude.md"
        mg_plan CLAUDE.md; MG_EDITED+=(CLAUDE.md)
        if [[ "$mg_shim" == "@AGENTS.md" ]]; then
            mg_act note "CLAUDE.md is the 2.x shim: it now imports the kit's standards, then AGENTS.md as before. Moving the team's own sections from AGENTS.md into CLAUDE.md (the 3.0 starter shape, kit/templates/workspace/CLAUDE.md) is yours to do; the kit-generic sections of AGENTS.md now load twice until then"
        else
            mg_kh_file="$MG_KIT/CLAUDE.kit.md"
            mg_norm_heads() { awk '/^## / { h = tolower(substr($0, 4)); gsub(/^[0-9§. ·-]+/, "", h); sub(/[ \t]+$/, "", h); print NR "\t" h }'; }
            mg_kitheads="$(mg_norm_heads < "$mg_kh_file" | cut -f 2)"
            while IFS=$'\t' read -r mg_n mg_hd; do
                [[ -n "$mg_hd" ]] || continue
                if printf '%s\n' "$mg_kitheads" | grep -xF -- "$mg_hd" >/dev/null; then
                    mg_act note "CLAUDE.md:$((mg_n + 3)) heading \"$mg_hd\" is also a heading of kit/CLAUDE.kit.md; both load now"
                fi
            done < <(mg_vread CLAUDE.md | tail -n +4 | mg_norm_heads)
        fi
    fi
fi

# M14: developer mode, when asked for.
if [[ $DEVELOPER -eq 1 ]]; then
    mg_dev_ok=0
    if [[ $DRY -eq 0 || "$MG_KIT" == "$WS/kit" ]]; then
        [[ "$(aw_git_elsewhere "$MG_KIT" symbolic-ref -q --short HEAD 2>/dev/null)" == main \
            && "$(mg_g config --get "submodule.$KNAME.update" 2>/dev/null)" == rebase \
            && "$(mg_g config --get pull.rebase 2>/dev/null)" == true ]] && mg_dev_ok=1
    fi
    if [[ $mg_dev_ok -eq 1 ]]; then
        mg_act skip "M14 developer mode (kit/ is on main, update=rebase, pull.rebase=true)"
    else
        mg_act run "kit/lib/setup/developer.sh --target $WS"
        if [[ $DRY -eq 0 ]]; then
            mg_child bash "$WS/kit/lib/setup/developer.sh" --target "$WS" || mg_stop M14 "kit/lib/setup/developer.sh failed"
        else
            # developer.sh has no check mode; the settings it keeps are read here instead.
            echo "    would put kit/ on main, tracking origin/main, without moving main backwards"
            [[ "$(mg_g config --get "submodule.$KNAME.update" 2>/dev/null)" == rebase ]] \
                || echo "    would set workspace submodule.$KNAME.update=rebase"
            [[ "$(mg_g config --get pull.rebase 2>/dev/null)" == true ]] || echo "    would set workspace pull.rebase=true"
            echo "    would check kit/'s hooks and the private word list its hooks read"
        fi
    fi
else
    mg_act skip "M14 developer mode (not asked for; --developer)"
fi

# M15: the engine creates the files the kit leaves to the team from 3.0 on, and records the ones
# already here as kept (an opaque one without opening it).
mg_team=""
if mg_vexists .claude/projects.md; then
    mg_team="$(mg_vread .claude/projects.md | awk 'NR == 1 && /^# / { s = $0; if (sub(/^# [^—]*— /, "", s)) print s; exit }')"
    # A stand-in (<team name>) or an unrendered placeholder (__TEAM__) is no answer.
    case "$mg_team" in *'<'*|*__*) mg_team="" ;; esac
fi
mg_eng=(--target "$WS" --gitignore merge)
[[ -n "$mg_team" ]] && mg_eng+=(--team "$mg_team")
mg_eng_needed=1
if [[ $MG_LEDGER -eq 1 && -f "$MG_KIT/install.sh" ]]; then
    mg_kr="kit"; [[ $DRY -eq 1 && -n "$OLD" ]] && mg_kr="$OLD"
    if mg_rep="$(bash "$MG_KIT/install.sh" "${mg_eng[@]}" --kit "$mg_kr" --dry-run 2>/dev/null)"; then
        printf '%s\n' "$mg_rep" | grep -E '^(Created|Merged|Added to \.gitignore)' >/dev/null || mg_eng_needed=0
    fi
fi
if [[ $mg_eng_needed -eq 0 ]]; then
    mg_act skip "M15 engine (nothing to create)"
else
    mg_show="kit/install.sh --target $WS --gitignore merge"
    [[ -n "$mg_team" ]] && mg_show+=" --team $(mg_q "$mg_team")"
    mg_act run "$mg_show"
    if [[ $DRY -eq 0 ]]; then
        bash "$WS/kit/install.sh" "${mg_eng[@]}" > "$MG_TMP/engine.out" 2>&1
        mg_rc=$?
        sed 's/^/    /' "$MG_TMP/engine.out"
        [[ $mg_rc -eq 0 ]] || mg_stop M15 "kit/install.sh exited $mg_rc"
        # The files the engine created or changed go into the commit.
        while IFS= read -r mg_p; do [[ -n "$mg_p" ]] && mg_plan "$mg_p"; done < <(awk '
            /^(Created|Merged|Added to \.gitignore)/ { on = 1; next }
            /^[^ ]/ { on = 0 }
            on && /^  [^ ]/ { s = substr($0, 3); sub(/  .*/, "", s); sub(/ \(.*/, "", s); print s }' "$MG_TMP/engine.out")
    else
        # The engine's own dry run names the files it would create or merge; they go into the plan as
        # the real run's do. .gitignore lines are M10's, above. The engine reads templates from a kit
        # inside the workspace: the kit checkout when it is 3.0 already, else this script's kit when
        # that sits in the workspace.
        mg_kr=""
        if [[ $MG_DRY_SELF -eq 0 && -n "$OLD" ]]; then mg_kr="$OLD"
        else case "$MG_SELF_KIT/" in "$WS"/*) mg_kr="${MG_SELF_KIT#"$WS"/}" ;; esac; fi
        if [[ -n "$mg_kr" ]] && mg_rep="$(bash "$MG_KIT/install.sh" "${mg_eng[@]}" --kit "$mg_kr" --dry-run 2>/dev/null)"; then
            while IFS=$'\t' read -r mg_how mg_p; do
                [[ -n "$mg_p" ]] || continue
                echo "    would $mg_how $mg_p"
                mg_plan "$mg_p"
            done < <(printf '%s\n' "$mg_rep" | awk '
                /^Created/ { on = "create"; next }
                /^Merged/ { on = "merge"; next }
                /^[^ ]/ { on = "" }
                on != "" && /^  [^ ]/ { s = substr($0, 3); sub(/  .*/, "", s); sub(/ \(.*/, "", s); print on "\t" s }')
        else
            echo "    (the files it creates are named once the kit checkout is 3.0: run the dry run again after --kit-from, or read the real run's list)"
        fi
    fi
fi
mg_vexists .claude/kit-templates.lock && mg_plan .claude/kit-templates.lock
[[ $DRY -eq 1 && $MG_LEDGER -eq 0 ]] && mg_plan .claude/kit-templates.lock

# M15b: --confirm-private-origin records origin as a private remote the person has confirmed.
if [[ $CONFIRM_ORIGIN -eq 1 ]]; then
    mg_origin="$(mg_g remote get-url origin 2>/dev/null)"
    if [[ -z "$mg_origin" ]]; then
        mg_act skip "M15b private origin (no origin remote)"
    else
        mg_norm="$(aw_norm_url "$mg_origin")"
        mg_listed=0
        if [[ $DRY -eq 1 && -f "$SHADOW/.claude/workspace.md" ]]; then mg_wsroot="$SHADOW"; else mg_wsroot="$WS"; fi
        while IFS=$'\t' read -r mg_u _ _; do [[ "$mg_u" == "$mg_norm" ]] && mg_listed=1; done < <(aw_private_remotes "$mg_wsroot")
        if [[ $mg_listed -eq 1 ]]; then
            mg_act skip "M15b private origin ($mg_norm is listed already)"
        else
            mg_date="$(date +%F)"
            # Written with its scheme (or as the plain path, for a local one), so it reads back to the
            # same normalised form, and with no user or token, which aw_norm_url has dropped.
            case "$mg_norm" in local:*) mg_rec="${mg_norm#local:}" ;; *) mg_rec="https://$mg_norm" ;; esac
            mg_bl="- **Private remote:** \`$mg_rec\` — confirmed $mg_date via person"
            mg_act edit ".claude/workspace.md: + Private remote $mg_norm, confirmed $mg_date via person"
            if [[ $DRY -eq 0 ]]; then
                [[ -f "$WS/.claude/workspace.md" ]] || mg_stop M15b ".claude/workspace.md is missing (the engine creates it at M15)"
                awk -v bl="$mg_bl" '
                    { print }
                    /^## Private remotes/ { sec = 1; next }
                    sec && /^## / { sec = 0 }
                    sec && !done && /^<!--.*-->[ \t]*$/ { print bl; done = 1 }
                    END { if (!done) exit 1 }' "$WS/.claude/workspace.md" > "$MG_TMP/workspace.md" \
                    || awk -v bl="$mg_bl" '
                        { print }
                        /^## Private remotes/ && !done { print ""; print bl; done = 1 }
                        END { if (!done) { print ""; print "## Private remotes"; print ""; print bl } }' "$WS/.claude/workspace.md" > "$MG_TMP/workspace.md"
                mg_vwrite .claude/workspace.md < "$MG_TMP/workspace.md"
            fi
            mg_plan .claude/workspace.md
        fi
    fi
fi

# M16: the map, in file order (the lines M0b ran are skipped).
if [[ ${#MAP_VERB[@]} -eq 0 ]]; then
    mg_act skip "M16 map (no --map)"
fi
mg_i=0 mg_subs_changed=0
MG_SUB_DESTS=()
while [[ $mg_i -lt ${#MAP_VERB[@]} ]]; do
    mg_v="${MAP_VERB[$mg_i]}" mg_a="${MAP_A[$mg_i]}" mg_b="${MAP_B[$mg_i]}" mg_more="${MAP_REST[$mg_i]}"
    if [[ "${MAP_DONE[$mg_i]}" == 1 ]]; then mg_i=$((mg_i + 1)); continue; fi
    mg_acted_before=$MG_ACTED
    case "$mg_v" in
        git-mv|submodule-mv|mv)
            if ! mg_vexists "$mg_a"; then
                if mg_vexists "$mg_b"; then mg_act skip "$mg_v $mg_a -> $mg_b (done: the destination exists)"
                else mg_act skip "$mg_v $mg_a -> $mg_b (not present here)"; fi
            elif mg_vexists "$mg_b"; then
                mg_act skip "$mg_v $mg_a -> $mg_b (destination exists)"
            elif [[ "$mg_v" == submodule-mv ]] && ! mg_vgitlink "$mg_a"; then
                mg_act skip "$mg_v $mg_a (not a gitlink here)"
            elif [[ "$mg_v" == git-mv ]] && ! mg_vtracked "$mg_a"; then
                mg_act skip "$mg_v $mg_a (not tracked: an mv line moves untracked content)"
            elif [[ "$mg_v" == mv ]] && mg_vtracked "$mg_a"; then
                mg_act skip "$mg_v $mg_a (tracked: a git-mv line moves it)"
            else
                if [[ "$mg_v" == mv ]]; then
                    mg_by="$(mg_ignored_by "$mg_a/")"; [[ -n "$mg_by" ]] || mg_by="$(mg_ignored_by "$mg_a")"
                    mg_move M16 "$mg_a" "$mg_b" "mv"
                    if [[ -n "$mg_by" && $DRY -eq 0 && -z "$(mg_ignored_by "$mg_b/")" && -z "$(mg_ignored_by "$mg_b")" ]]; then
                        mg_act note "$mg_b is not ignored as $mg_a was ($mg_by): its files now show as untracked"
                    fi
                else
                    mg_move M16 "$mg_a" "$mg_b" "git mv"
                fi
                mg_n=0
                while IFS= read -r mg_l || [[ -n "$mg_l" ]]; do
                    mg_n=$((mg_n + 1))
                    case "$mg_l" in "$mg_a"|"$mg_a"/*|"!$mg_a"|"!$mg_a"/*|"/$mg_a"|"/$mg_a"/*|"!/$mg_a"|"!/$mg_a"/*)
                        mg_act note ".gitignore:$mg_n $mg_l names $mg_a; the map line gitignore-rewrite $mg_a $mg_b carries it over" ;;
                    esac
                done < <(mg_vread .gitignore 2>/dev/null)
            fi ;;
        retire) mg_retire M16 "$mg_a" ;;
        untrack) mg_untrack "$mg_a" ;;
        submodule-register) mg_register "$mg_a" "$mg_b" "$mg_more" ;;
        header) mg_header "$mg_a" "$mg_more" ;;
        gitignore-add)
            if mg_ignore_has "$mg_a"; then mg_act skip "gitignore-add $mg_a (in .gitignore already)"
            else mg_act edit ".gitignore: + $mg_a"; mg_ignore_add "$mg_a"; fi ;;
        gitignore-rewrite)
            mg_ph="$(mg_vphys .gitignore 2>/dev/null)" || mg_ph=""
            mg_nums=""
            if [[ -n "$mg_ph" && -f "$mg_ph" ]]; then
                mg_nums="$(awk -v f="$mg_a" -v t="$mg_b" -v out="$MG_TMP/gi-rw" '
                    { l = $0; pre = ""
                      if (substr(l, 1, 1) == "!") { pre = "!"; l = substr(l, 2) }
                      if (substr(l, 1, 1) == "/" && substr(f, 1, 1) != "/") { pre = pre "/"; l = substr(l, 2) }
                      if (index(l, f) == 1) { print pre t substr(l, length(f) + 1) > out; print NR } else print $0 > out }' "$mg_ph")"
            fi
            if [[ -z "$mg_nums" ]]; then
                mg_act skip "gitignore-rewrite $mg_a -> $mg_b (no .gitignore line starts with it)"
            else
                for mg_n in $mg_nums; do mg_act edit ".gitignore:$mg_n $mg_a -> $mg_b"; done
                mg_vwrite .gitignore < "$MG_TMP/gi-rw"; MG_EDITED_GITIGNORE=1
            fi ;;
        rewrite)
            MG_GLOBS=()
            if [[ -n "$mg_more" ]]; then
                while IFS= read -r mg_g1; do [[ -n "$mg_g1" ]] && MG_GLOBS+=("$mg_g1"); done < <(printf '%s\n' "$mg_more" | tr '\t' '\n')
                mg_scope=globs
            else
                mg_scope=all
            fi
            mg_hits=0
            while IFS=$'\t' read -r mg_vp mg_ph; do
                [[ -n "$mg_vp" ]] || continue
                # Globs reach into the default dated records when they name them; a historical line
                # holds in either scope.
                [[ "$mg_scope" == all ]] && mg_is_historical "$mg_vp" && continue
                mg_map_historical "$mg_vp" && continue
                mg_before=${#MG_EDITED[@]}
                mg_rewrite_in "$mg_vp" "$mg_a" "$mg_b" path "$MG_KEEP"
                [[ ${#MG_EDITED[@]} -gt $mg_before ]] && mg_hits=1
            done < <(mg_candidates "$mg_a" "$mg_scope")
            [[ $mg_hits -eq 1 ]] || mg_act skip "rewrite $mg_a -> $mg_b (nothing left to rewrite)" ;;
        keep) mg_act skip "keep $mg_a (protects the literal in every rewrite)" ;;
        historical)
            # The files it names, listed under its line: M7, rewrite and M18 leave them as written.
            mg_hn=0 mg_hl=""
            while IFS=$'\t' read -r mg_vp mg_ph; do
                case "$mg_vp" in kit|kit/*) continue ;; esac
                # shellcheck disable=SC2053
                [[ "$mg_vp" == $mg_a || "$mg_vp" == $mg_a/* ]] || continue
                mg_hn=$((mg_hn + 1)); mg_hl+="    $mg_vp"$'\n'
            done < <(mg_vlist)
            mg_act skip "historical $mg_a (dated records: $mg_hn, kept as written)"
            printf '%s' "$mg_hl" ;;
        private-term)
            # The term itself is not printed: the run's output may be kept or shared.
            if mg_vread .claude/private-terms.local 2>/dev/null | grep -qxF -- "$mg_a"; then
                mg_act skip "private-term (map line ${MAP_LN[$mg_i]}: in .claude/private-terms.local already)"
            else
                mg_act edit ".claude/private-terms.local: + the term on map line ${MAP_LN[$mg_i]}"
                { if mg_vexists .claude/private-terms.local; then mg_vread .claude/private-terms.local; else
                      printf '%s\n' "# Private terms: names the kit's hooks refuse in anything committed or pushed to the kit." \
                          "# One extended regex per line, matched whole-word in any case. Yours; gitignored; never copied into kit/."
                  fi; printf '%s\n' "$mg_a"; } > "$MG_TMP/terms"
                mg_vwrite .claude/private-terms.local < "$MG_TMP/terms"
            fi ;;
        note) mg_act note "$mg_a" ;;
    esac
    case "$mg_v" in submodule-mv|submodule-register)
        if [[ $MG_ACTED -gt $mg_acted_before ]]; then
            mg_subs_changed=1
            if [[ "$mg_v" == submodule-mv ]]; then MG_SUB_DESTS+=("$mg_b"); else MG_SUB_DESTS+=("$mg_a"); fi
        fi ;;
    esac
    mg_i=$((mg_i + 1))
done
# A gitlink the map moved or registered may now be a project repository, which M8 and M9 ran too early
# to see: its hook stubs and its update=rebase setting are set here.
if [[ $mg_subs_changed -eq 1 ]]; then
    mg_act run "kit/lib/setup/gitconfig.sh --target $WS --hooks --submodules"
    if [[ $DRY -eq 0 ]]; then
        mg_child bash "$WS/kit/lib/setup/gitconfig.sh" --target "$WS" --hooks --submodules \
            || mg_stop M16 "kit/lib/setup/gitconfig.sh --hooks --submodules failed"
    else
        # The moves have not happened, so gitconfig.sh cannot be asked; each moved or registered
        # submodule that lands in a project folder is named instead.
        for mg_p in ${MG_SUB_DESTS[@]+"${MG_SUB_DESTS[@]}"}; do
            mg_isproj=0
            if [[ $MG_HAVE_CONV -eq 1 ]]; then
                while IFS= read -r mg_pat; do
                    [[ -n "$mg_pat" && "$(projects_match "$mg_pat" "$mg_p")" == "$mg_p" ]] && mg_isproj=1
                done <<EOF
$PROJECT_PATTERNS
EOF
            fi
            if [[ $mg_isproj -eq 1 ]]; then
                echo "    would set $mg_p aw-hooks and core.hooksPath (once it is initialised), and . submodule.<its name>.update=rebase"
            else
                echo "    $mg_p is not a project folder: it counts as outside the kit's concern, and submodule.recurse stays held"
            fi
        done
    fi
fi

# M17: the skills bridge, where there are skills to bridge.
if mg_vexists skills || mg_vexists .claude/skills; then
    if bash "$MG_KIT/scripts/skills-bridge.sh" --target "$WS" --check >/dev/null 2>&1; then
        mg_act skip "M17 skills bridge (current)"
    else
        mg_act run "kit/scripts/skills-bridge.sh --target $WS"
        if [[ $DRY -eq 0 ]]; then
            mg_child bash "$WS/kit/scripts/skills-bridge.sh" --target "$WS" || mg_stop M17 "kit/scripts/skills-bridge.sh failed"
        fi
    fi
else
    mg_act skip "M17 skills bridge (no skills/ or .claude/skills/)"
fi

# M18: what still names a path this run moved, outside the kit, opaque files and dated records.
mg_left_refs=0
mg_i=0
while [[ $mg_i -lt ${#MG_MOVED_FROM[@]} ]]; do
    mg_from="${MG_MOVED_FROM[$mg_i]}" mg_to="${MG_MOVED_TO[$mg_i]}"
    # A top-level folder with a one-word name (ai, public) is looked for as "<from>/": the bare name is
    # also an ordinary word. A longer path is distinctive as it stands.
    if [[ "$mg_from" != */* && "$mg_from" != *.* ]]; then mg_from="$mg_from/" mg_to="$mg_to/"; fi
    while IFS=$'\t' read -r mg_vp mg_ph; do
        [[ -n "$mg_vp" ]] || continue
        mg_is_historical "$mg_vp" && continue
        { printf '%s\n' "$mg_to"; cat "$MG_KEEP"; } > "$MG_TMP/keep-to"
        for mg_n in $(mg_replace "$mg_ph" "" "$mg_from" "$mg_to" ref "$MG_TMP/keep-to"); do
            mg_act note "$mg_vp:$mg_n still names $mg_from"
            mg_left_refs=1
        done
    done < <(mg_candidates "$mg_from" all)
    mg_i=$((mg_i + 1))
done
[[ $mg_left_refs -eq 1 ]] || mg_act skip "M18 leftover references (none)"

# ---- The commit to make --------------------------------------------------------------------------
mg_mark_staged
[[ $DRY -eq 0 && -n "$MG_STATE_FILE" ]] && rm -f "$MG_STATE_FILE"
echo
if [[ $DRY -eq 1 ]]; then
    echo "Dry run: nothing was changed. Run it again without --dry-run to make these changes."
    echo
fi
[[ $MG_EDITED_GITIGNORE -eq 1 ]] && mg_plan .gitignore
mg_add=()
for mg_p in .gitmodules kit .claude/settings.json .gitignore CLAUDE.md .claude/kit-templates.lock ${MG_PLAN[@]+"${MG_PLAN[@]}"}; do
    mg_seen=0
    for mg_q1 in ${mg_add[@]+"${mg_add[@]}"}; do [[ "$mg_q1" == "$mg_p" ]] && mg_seen=1; done
    [[ $mg_seen -eq 0 ]] || continue
    mg_inplan=0
    for mg_q1 in ${MG_PLAN[@]+"${MG_PLAN[@]}"}; do [[ "$mg_q1" == "$mg_p" ]] && mg_inplan=1; done
    [[ $mg_inplan -eq 1 ]] || continue
    if [[ $DRY -eq 0 ]]; then
        [[ -e "$WS/$mg_p" ]] || continue
        mg_g check-ignore -q --no-index -- "$mg_p" 2>/dev/null && ! mg_g ls-files --error-unmatch -- "$mg_p" >/dev/null 2>&1 && continue
    else
        # The dry run has not written its .gitignore lines, so it reads its own copy of the file: a
        # path the run is about to ignore (an untracked project, say) would make git add refuse the line.
        mg_vignored "$mg_p" && ! mg_vtracked "$mg_p" && continue
    fi
    mg_add+=("$mg_p")
done
if [[ $((MG_ACTED + MG_PRIOR_ACTED)) -eq 0 ]]; then
    echo "Nothing changed in this run. Anything an earlier run changed and is not committed yet shows in git status."
else
    echo "Commit plan. The migration commits nothing; these are the commands to run when you are ready."
    [[ -n "$MG_PRIOR_STOP" ]] && echo "It covers the earlier run that stopped at $MG_PRIOR_STOP as well as this one."
    if [[ ${#MG_STAGED[@]} -gt 0 ]]; then
        echo "The moves and removals are staged already (git status lists them):"
        printf '%s\n' "${MG_STAGED[@]}" | awk '!seen[$0]++ { print "  " $0 }'
    fi
    if [[ ${#mg_add[@]} -gt 0 ]]; then
        mg_cmd="git add"
        for mg_p in "${mg_add[@]}"; do mg_cmd+=" $(mg_q "$mg_p")"; done
        echo "Then:"
        echo "  $mg_cmd"
    fi
    echo "  git commit -m \"Move to the kit 3.0 layout\""
fi
echo
echo "Next:"
echo "  1. Run kit/setup.sh. Its stage 4 confirms the origin is private and records it."
echo "  2. Restart Claude Code and approve the plugins."
echo "  3. Once the commit is made, check that /plugin shows agentic-workspace at"
echo "       $WS/kit"
echo "     If it shows the old path, your user settings still name it there. Re-point the user entry alone:"
echo "     a remove without --scope user also takes the marketplace and the three plugins out of the"
echo "     workspace's .claude/settings.json, and uninstalls them. Quit Claude Code, then run these one at"
echo "     a time:"
echo "       claude plugin marketplace remove --scope user agentic-workspace"
echo "       claude plugin marketplace add --scope user $(mg_q "$WS/kit")"
echo "       claude plugin install closeout@agentic-workspace"
echo "       claude plugin install projects@agentic-workspace"
echo "       claude plugin install workspace@agentic-workspace"
echo "       git -C $(mg_q "$WS") diff -- .claude/settings.json"
echo "     The last one prints nothing when the workspace's settings are as committed. If it prints a"
echo "     change, put the file back:"
echo "       git -C $(mg_q "$WS") checkout -- .claude/settings.json"
echo "  4. Look in _delete/ and delete what you do not want back."
exit 0
