#!/usr/bin/env bash
# scripts/skills-bridge.sh: the skills bridge. Writes the kit's commands as kit-* skills, and copies the
# workspace's own skills from skills/, into .claude/skills/, where a surface that loads skills from a
# folder (Cowork) finds them. Also reached as kit/setup.sh skills.
#
#   bash kit/scripts/skills-bridge.sh [--target WS] [--dry-run] [--check] [--no-user]
#
# The bridge owns only what its manifest, .claude/skills/.kit-generated, lists: it refreshes and removes
# those folders and leaves every other folder in .claude/skills/ as it is. A folder it would write that
# is already there and not listed is a clash: reported, never overwritten. Kit commands named under
# "Kit skills not bridged" in .claude/workspace.md are left out.
#
# A folder is compared before it is written, so a run with nothing new changes no file. Copies are real
# folders, never links, because Cowork's scanner does not follow links.
#
# Exit: 0 done (clashes are reported, not failures) · 1 --check found something to change, or the run
# stopped (the generator failed, or .claude/skills/ could not be written) · 2 usage, not a workspace, or a
# target inside the kit checkout.
set -uo pipefail

SELF_KIT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
# shellcheck source=lib/common.sh
. "$SELF_KIT/lib/common.sh"

usage() {
    cat <<'USAGE'
Usage: kit/scripts/skills-bridge.sh [--target WS] [--dry-run] [--check] [--no-user]

Writes the kit's skills (kit-*) and the workspace's own skills (from skills/) into .claude/skills/, and
lists what it wrote in .claude/skills/.kit-generated.

  --target WS   the workspace (default: the repository this kit checkout sits in)
  --dry-run     say what would change, write nothing
  --check       as --dry-run, and exit 1 when anything would change
  --no-user     write only the kit's skills; the workspace's own are left as they are

Run it from a terminal (kit/setup.sh skills): an agent's sandbox may refuse writes to .claude/skills/.
USAGE
}

TARGET="" DRY=0 CHECK=0 NOUSER=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        --target) [[ $# -ge 2 && -n "$2" ]] || { usage >&2; exit 2; }; TARGET="$2"; shift 2 ;;
        --dry-run) DRY=1; shift ;;
        --check) CHECK=1; DRY=1; shift ;;
        --no-user) NOUSER=1; shift ;;
        -h|--help) usage; exit 0 ;;
        *) printf 'skills-bridge: unknown option %s\n\n' "$1" >&2; usage >&2; exit 2 ;;
    esac
done

stop() { local code="$1"; shift; printf 'skills-bridge: %s\n' "$*" >&2; exit "$code"; }

# The workspace: --target, else the superproject of the kit checkout this script lives in, else here.
if [[ -z "$TARGET" ]]; then
    TARGET="$(git --no-optional-locks -C "$SELF_KIT" rev-parse --show-superproject-working-tree 2>/dev/null)"
    [[ -n "$TARGET" ]] || TARGET="$PWD"
fi
[[ -d "$TARGET" ]] || stop 2 "$TARGET is not a folder"
WS="$(cd "$TARGET" && pwd -P)"

# A kit checkout is public and holds no workspace's skills. Refused: the checkout this script belongs
# to, anything inside it, and any folder whose repository is itself a kit checkout.
case "$WS/" in
    "$SELF_KIT"/*) stop 2 "$WS is inside the kit checkout; give the workspace with --target" ;;
esac
ws_top="$(aw_git_elsewhere "$WS" rev-parse --show-toplevel 2>/dev/null)"
for d in "$WS" ${ws_top:+"$ws_top"}; do
    if [[ -f "$d/CLAUDE.kit.md" && -f "$d/.claude-plugin/marketplace.json" ]]; then
        stop 2 "$WS is inside a kit checkout; give the workspace with --target"
    fi
done
[[ -f "$WS/kit/install.sh" && -f "$WS/kit/CLAUDE.kit.md" ]] \
    || stop 2 "$WS is not a workspace: it has no kit checkout at kit/"

SK="$WS/.claude/skills"
MANIFEST="$SK/.kit-generated"
[[ ! -L "$SK" ]] || stop 1 ".claude/skills is a link; the bridge writes real folders there, so make it a folder first"

tmp="$(mktemp -d "${TMPDIR:-/tmp}/aw-bridge.XXXXXX")" || stop 1 "could not make a temporary folder"
trap 'rm -rf "$tmp"' EXIT
NL=$'\n' TAB=$'\t'
# in_list <word> <newline-separated list>
in_list() { case "$NL$2$NL" in *"$NL$1$NL"*) return 0 ;; esac; return 1; }
# ok_name <folder>: a single path segment the bridge may create or remove.
ok_name() { [[ -n "$1" && "$1" != . && "$1" != .. && "$1" != */* && "$1" != .* ]]; }
# marker_src <SKILL.md>: the command a generated skill came from, from its marker line.
marker_src() { sed -n 's/.*Generated by install\.sh from \(plugins\/[^:]*\.md\):.*/\1/p' "$1" 2>/dev/null | head -n 1; }

# 1. The skip list: "Kit skills not bridged" in .claude/workspace.md. Its value is the backticked span
# straight after the label; with none there (the template's "none — …"), nothing is skipped. Items are
# the command's skill name (closeout, workspace-hygiene); kit-workspace-hygiene and /workspace:hygiene
# are read the same way.
skip_names=""
skip_line="$(_aw_remote_lines "$WS" "Kit skills not bridged" | head -n 1)"
if [[ -n "$skip_line" ]]; then
    v="${skip_line#*\*\*Kit skills not bridged:\*\*}"
    v="${v#"${v%%[![:space:]]*}"}"
    if [[ "$v" == \`* ]]; then
        v="${v#\`}"; v="${v%%\`*}"
        old_ifs="$IFS"; IFS=','
        for item in $v; do
            item="${item#"${item%%[![:space:]]*}"}"; item="${item%"${item##*[![:space:]]}"}"
            item="${item#/}"; item="${item//:/-}"; item="${item#kit-}"
            [[ -n "$item" && "$item" != none ]] || continue
            in_list "$item" "$skip_names" || skip_names="${skip_names:+$skip_names$NL}$item"
        done
        IFS="$old_ifs"
    fi
fi

# The kit's commands, each as its skill name and source; a command named after its plugin keeps its bare
# name (closeout), the rest are <plugin>-<command>, as the generator names them.
kit_cmds="" skip_src=""
for src in "$WS"/kit/plugins/*/commands/*.md; do
    [[ -f "$src" ]] || continue
    p="${src#"$WS"/kit/plugins/}"; p="${p%%/*}"; c="$(basename "$src" .md)"
    n="$c"; [[ "$p" == "$c" ]] || n="$p-$c"
    kit_cmds="${kit_cmds:+$kit_cmds$NL}$n"
    in_list "$n" "$skip_names" && skip_src="${skip_src:+$skip_src$NL}kit-$n${TAB}plugins/$p/commands/$c.md"
done

# 2. Generate the kit's skills into a temporary folder, with the kit- prefix and without the skipped ones.
skip_csv="$(printf '%s' "$skip_names" | tr '\n' ',')"
gen_args=(--skills-only --target "$WS" --skills-dir "$tmp/gen" --skills-prefix kit-)
[[ -z "$skip_csv" ]] || gen_args+=(--skills-skip "$skip_csv")
if ! bash "$WS/kit/install.sh" "${gen_args[@]}" </dev/null >"$tmp/gen.log" 2>&1; then
    printf "skills-bridge: the kit's skill generator failed (kit/install.sh --skills-only); nothing was written.\n" >&2
    tail -n 5 "$tmp/gen.log" | sed 's/^/  /' >&2
    exit 1
fi

# The folders this run produces: origin, folder, source, staged copy — four parallel arrays.
w_origin=() w_name=() w_src=() w_stage=()
for f in "$tmp"/gen/*/SKILL.md; do
    [[ -f "$f" ]] || continue
    n="$(basename "$(dirname "$f")")"
    case "$n" in
        kit-*) ;;
        *) stop 1 "the generator wrote $n without the kit- prefix; kit/install.sh is older than this bridge" ;;
    esac
    in_list "${n#kit-}" "$skip_names" && continue
    w_origin+=(kit) w_name+=("$n") w_src+=("$(marker_src "$f")") w_stage+=("$tmp/gen/$n")
done

# User skills: every skills/<name>/ that is not a dot-folder and has a SKILL.md, copied with links
# followed (a skill that is a submodule arrives as plain files), .git and .claude taken out, modes kept.
clash_lines="" legacy_lines="" user_names=""
if [[ $NOUSER -eq 0 ]]; then
    mkdir -p "$tmp/user"
    for d in "$WS"/skills/*/; do
        d="${d%/}"; n="$(basename "$d")"
        if [[ ! -f "$d/SKILL.md" ]] || ! ok_name "$n"; then continue; fi
        case "$n" in
            kit-*) clash_lines+="$n${TAB}skills/$n: the kit- prefix is the kit's; rename the skill to bridge it$NL"; continue ;;
        esac
        # A 2.x installer's generated skill is the kit's, not the workspace's; the migration retires it.
        if grep -qs 'Generated by install.sh from plugins/' "$d/SKILL.md"; then
            legacy_lines+="$n${TAB}skills/$n was generated by the kit's 2.x installer; kit/setup.sh migrate retires it$NL"
            continue
        fi
        if ! cp -RLp "$d" "$tmp/user/$n" 2>"$tmp/cp.err"; then
            clash_lines+="$n${TAB}skills/$n could not be copied ($(head -n 1 "$tmp/cp.err")); left out$NL"
            continue
        fi
        find "$tmp/user/$n" \( -name .git -o -name .claude \) -prune -exec rm -rf {} + 2>/dev/null
        user_names="${user_names:+$user_names$NL}$n"
    done
    while IFS= read -r n; do
        [[ -n "$n" ]] || continue
        w_origin+=(user) w_name+=("$n") w_src+=("skills/$n") w_stage+=("$tmp/user/$n")
    done <<EOF
$(printf '%s\n' "$user_names" | LC_ALL=C sort)
EOF
fi

# 3. The manifest: origin<TAB>folder<TAB>source. Lines that do not parse are left out of the rewrite.
have_manifest=0 listed="" listed_user_lines=""
if [[ -f "$MANIFEST" ]]; then
    have_manifest=1
    while IFS=$'\t' read -r o n s; do
        case "$o" in ''|\#*) continue ;; esac
        ok_name "$n" || continue
        case "$o" in
            kit|user)
                listed="${listed:+$listed$NL}$n"
                [[ "$o" == user ]] && listed_user_lines+="$o${TAB}$n${TAB}$s$NL" ;;
        esac
    done < "$MANIFEST"
fi

# same_dir <target> <staged>: 0 when the target is a real folder with the staged content and modes.
same_dir() {
    [[ -d "$1" && ! -L "$1" ]] || return 1
    [[ -z "$(find "$1" \( -name .git -o -name .claude \) 2>/dev/null | head -n 1)" ]] || return 1
    aw_git_elsewhere "$tmp" -c core.fileMode=true diff --no-index --quiet --no-ext-diff --no-textconv \
        -- "$1" "$2" >/dev/null 2>&1
}

# The plan. Lines are printed in the order kit, user, skip, stale, removed, clash, legacy; actions are
# "remove <folder>" and "write <index>", applied after the plan unless this is a dry run or a check.
out_kit="" out_user="" out_stale="" out_removed="" out_left=""
actions="" changes=0 n_kit=0 n_user=0 n_stale=0 n_removed=0
manifest_body=""
wanted=""
i=0
while [[ $i -lt ${#w_name[@]} ]]; do
    o="${w_origin[$i]}" n="${w_name[$i]}" t="$SK/${w_name[$i]}"
    wanted="${wanted:+$wanted$NL}$n"
    verb=written; [[ "$o" == user ]] && verb=copied
    state=""
    if in_list "$n" "$listed"; then
        if [[ ! -e "$t" && ! -L "$t" ]]; then state=stale
        elif same_dir "$t" "${w_stage[$i]}"; then state=current
        else state=replace; fi
    elif [[ ! -e "$t" && ! -L "$t" ]]; then
        state=new
    elif [[ $have_manifest -eq 0 ]] && { [[ "$o" == user ]] || grep -qs 'Generated by install.sh from plugins/' "$t/SKILL.md"; }; then
        # First run: a folder of the same name is an older sync script's mirror of this skill, or the
        # kit's own generated folder; either way it is the bridge's to refresh from here on.
        if same_dir "$t" "${w_stage[$i]}"; then state=adopt-current; else state=adopt; fi
    else
        clash_lines+="$n${TAB}already in .claude/skills/ and not listed in .kit-generated; left as it is$NL"
        i=$((i + 1)); continue
    fi
    case "$state" in
        stale) out_stale+="$n$NL"; n_stale=$((n_stale + 1)); actions+="write $i$NL"; changes=$((changes + 1)) ;;
        current) line="current" ;;
        adopt-current) line="current (adopted)" ;;
        replace) line="$verb"; actions+="remove $n${NL}write $i$NL"; changes=$((changes + 1)) ;;
        adopt) line="$verb (adopted)"; actions+="remove $n${NL}write $i$NL"; changes=$((changes + 1)) ;;
        new) line="$verb"; actions+="write $i$NL"; changes=$((changes + 1)) ;;
    esac
    if [[ "$state" != stale ]]; then
        if [[ "$o" == kit ]]; then out_kit+="$n  $line$NL"; else out_user+="$n  $line$NL"; fi
    fi
    if [[ "$o" == kit ]]; then n_kit=$((n_kit + 1)); else n_user=$((n_user + 1)); fi
    manifest_body+="$o${TAB}$n${TAB}${w_src[$i]}$NL"
    i=$((i + 1))
done

# Listed folders this run no longer produces are removed. With --no-user, the workspace's own copies
# are not being refreshed, so their lines stay as they were.
while IFS= read -r n; do
    [[ -n "$n" ]] || continue
    in_list "$n" "$wanted" && continue
    if [[ $NOUSER -eq 1 ]] && printf '%s' "$listed_user_lines" | awk -F '\t' -v n="$n" '$2 == n { f = 1 } END { exit !f }'; then
        continue
    fi
    out_removed+="$n$NL"; n_removed=$((n_removed + 1)); changes=$((changes + 1))
    { [[ -e "$SK/$n" || -L "$SK/$n" ]] && actions+="remove $n$NL"; } || true
done <<EOF
$listed
EOF
[[ $NOUSER -eq 0 ]] || manifest_body+="$listed_user_lines"

# Folders nobody asked for: a 2.x generated skill is reported as legacy on every run; anything else is
# the workspace's own and is named once, on the first run.
for d in "$SK"/*; do
    [[ -e "$d" || -L "$d" ]] || continue
    n="$(basename "$d")"
    in_list "$n" "$wanted" && continue
    in_list "$n" "$listed" && continue
    case "$NL$clash_lines" in *"$NL$n${TAB}"*) continue ;; esac
    if [[ "$n" != kit-* ]] && grep -qs 'Generated by install.sh from plugins/' "$d/SKILL.md"; then
        repl="kit-$n"; in_list "$n" "$kit_cmds" || repl="a kit- skill"
        legacy_lines+="$n${TAB}the kit's older unprefixed skill; $repl replaces it (kit/setup.sh migrate retires it)$NL"
    elif [[ $have_manifest -eq 0 ]]; then
        out_left+="$n$NL"
    fi
done

# The manifest as this run leaves it; written only when it differs.
{
    printf '# Written by kit/scripts/skills-bridge.sh. Lists every folder in .claude/skills/ this script wrote; it\n'
    printf '# deletes and refreshes only these. Folders not listed are left as they are.\n'
    printf '# origin\tfolder\tsource\n'
    printf '%s' "$manifest_body" | awk -F '\t' '$1 == "kit"' | LC_ALL=C sort -t "$(printf '\t')" -k2,2
    printf '%s' "$manifest_body" | awk -F '\t' '$1 == "user"' | LC_ALL=C sort -t "$(printf '\t')" -k2,2
    [[ -z "$skip_src" ]] || printf '%s\n' "$skip_src" | LC_ALL=C sort | sed "s/^/skip${TAB}/"
} > "$tmp/manifest"
cmp -s "$tmp/manifest" "$MANIFEST" 2>/dev/null || changes=$((changes + 1))

# Apply: removals first, then the kit's folders, then the workspace's, then the manifest.
if [[ $DRY -eq 0 ]]; then
    mkdir -p "$SK" 2>/dev/null && [[ -w "$SK" ]] \
        || stop 1 ".claude/skills/ cannot be written here (an agent's sandbox may refuse it); run kit/setup.sh skills from a terminal"
    while IFS=' ' read -r verb arg; do
        case "$verb" in
            remove)
                ok_name "$arg" || continue
                rm -rf -- "${SK:?}/$arg" || stop 1 "could not remove .claude/skills/$arg" ;;
            write)
                cp -Rp "${w_stage[$arg]}" "$SK/${w_name[$arg]}" || stop 1 "could not write .claude/skills/${w_name[$arg]}" ;;
        esac
    done <<EOF
$actions
EOF
    cmp -s "$tmp/manifest" "$MANIFEST" 2>/dev/null || cp "$tmp/manifest" "$MANIFEST" \
        || stop 1 "could not write .claude/skills/.kit-generated"
fi

# The report.
[[ $CHECK -eq 1 ]] && echo "Check only — nothing written."
[[ $CHECK -eq 0 && $DRY -eq 1 ]] && echo "Dry run — nothing written."
echo "Skills bridge: $SK"
row() { printf '  %-7s %s\n' "$1" "$2"; }
while IFS= read -r l; do [[ -n "$l" ]] && row kit "$l"; done <<EOF
$out_kit
EOF
while IFS= read -r l; do [[ -n "$l" ]] && row user "$l"; done <<EOF
$out_user
EOF
n_skip=0
while IFS=$'\t' read -r n _; do
    [[ -n "$n" ]] || continue
    n_skip=$((n_skip + 1)); row skip "$n  (Kit skills not bridged)"
done <<EOF
$skip_src
EOF
while IFS= read -r n; do
    [[ -n "$n" ]] || continue
    in_list "$n" "$kit_cmds" || row skip "kit-$n  (Kit skills not bridged; no kit command has this name)"
done <<EOF
$skip_names
EOF
while IFS= read -r l; do [[ -n "$l" ]] && row stale "$l  (listed, missing; regenerated)"; done <<EOF
$out_stale
EOF
while IFS= read -r l; do [[ -n "$l" ]] && row removed "$l  (listed; no longer produced)"; done <<EOF
$out_removed
EOF
n_clash=0
while IFS=$'\t' read -r n why; do
    [[ -n "$n" ]] || continue
    n_clash=$((n_clash + 1)); row clash "$n  — $why"
done <<EOF
$clash_lines
EOF
n_legacy=0
while IFS=$'\t' read -r n why; do
    [[ -n "$n" ]] || continue
    n_legacy=$((n_legacy + 1)); row legacy "$n  — $why"
done <<EOF
$legacy_lines
EOF
while IFS= read -r l; do [[ -n "$l" ]] && row left "$l  (not the bridge's; left as it is)"; done <<EOF
$out_left
EOF
printf '%s kit, %s user, %s skipped, %s stale, %s removed, %s clashes, %s legacy.\n' \
    "$n_kit" "$n_user" "$n_skip" "$n_stale" "$n_removed" "$n_clash" "$n_legacy"

[[ $CHECK -eq 1 && $changes -gt 0 ]] && exit 1
exit 0
